# Generated by Django 5.2.7 on 2026-01-23 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("max_appointments", models.PositiveIntegerField(default=1)),
                ("current_bookings", models.PositiveIntegerField(default=0)),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("sample_collection", "Sample Collection"),
                            ("consultation", "Consultation"),
                            ("result_discussion", "Result Discussion"),
                            ("general", "General Visit"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_slots",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_id", models.CharField(max_length=20, unique=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("sample_collection", "Sample Collection"),
                            ("consultation", "Consultation"),
                            ("result_discussion", "Result Discussion"),
                            ("test_request", "New Test Request"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(
                        blank=True, help_text="Patient's notes about the visit"
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Any special needs (wheelchair access, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("confirmation_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booked_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="labs.patient",
                    ),
                ),
                (
                    "test_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment",
                        to="labs.testrequest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="appointment.appointmentslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlotTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Consultation')", max_length=100
                    ),
                ),
                ("start_time", models.TimeField(help_text="Slot start time")),
                ("end_time", models.TimeField(help_text="Slot end time")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Slot duration in minutes"
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.CharField(
                        choices=[
                            ("weekdays", "Weekdays (Mon-Fri)"),
                            ("weekends", "Weekends (Sat-Sun)"),
                            ("daily", "Daily"),
                            ("specific_days", "Specific Days of Week"),
                        ],
                        default="weekdays",
                        max_length=20,
                    ),
                ),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        default=1, help_text="Max bookings per slot"
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("sample_collection", "Sample Collection"),
                            ("consultation", "Consultation"),
                            ("result_discussion", "Result Discussion"),
                            ("general", "General Visit"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Prep instructions (e.g., 'Fasting required for 12 hours')",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_slot_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_templates",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["vendor", "date", "is_active"],
                name="appointment_vendor__1ab5b9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmentslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_bookings__lte", models.F("max_appointments"))
                ),
                name="slot_capacity_not_exceeded",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["vendor", "status"], name="appointment_vendor__070a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_id"], name="appointment_appoint_aca1f9_idx"
            ),
        ),
    ]
