# Generated by Django 5.2.7 on 2026-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("sample_collection", "Sample Collection"),
                    ("consultation", "Consultation"),
                    ("result_discussion", "Result Discussion"),
                    ("general", "General Visit"),
                ],
                default="consultation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentslottemplate",
            name="name",
            field=models.CharField(
                help_text="Template name (e.g., 'Consultation')", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="appointmentslottemplate",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("sample_collection", "Sample Collection"),
                    ("consultation", "Consultation"),
                    ("result_discussion", "Result Discussion"),
                    ("general", "General Visit"),
                ],
                default="consultation",
                max_length=20,
            ),
        ),
    ]
