# Generated by Django 5.2.7 on 2026-01-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointmentslot_slot_type_and_more"),
        ("labs", "0005_patient_is_shadow"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentslot",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Prep instructions (e.g., 'Fasting required for 12 hours')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointmentslottemplate",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Prep instructions (e.g., 'Fasting required for 12 hours')",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked patient record (created if doesn't exist)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="labs.patient",
            ),
        ),
    ]
