# Generated by Django 5.2.7 on 2026-01-10 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_appointmentslot_instructions_and_more"),
        ("labs", "0005_patient_is_shadow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_patient_386c12_idx",
        ),
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="visitor_date_of_birth",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="visitor_email",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="visitor_first_name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="visitor_gender",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="visitor_last_name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="visitor_phone",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="booked_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="labs.patient",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="test_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment",
                to="labs.testrequest",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="current_bookings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="max_appointments",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
