# Generated by Django 5.2.7 on 2026-02-19 10:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicianProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, help_text="Medical license number", max_length=100
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("general_practice", "General Practice"),
                            ("internal_medicine", "Internal Medicine"),
                            ("pediatrics", "Pediatrics"),
                            ("cardiology", "Cardiology"),
                            ("endocrinology", "Endocrinology"),
                            ("hematology", "Hematology"),
                            ("oncology", "Oncology"),
                            ("infectious_disease", "Infectious Disease"),
                            ("pathology", "Pathology"),
                            ("other", "Other"),
                        ],
                        default="general_practice",
                        max_length=50,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, help_text="Hospital/Clinic name", max_length=255
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department within organization",
                        max_length=100,
                    ),
                ),
                (
                    "qualifications",
                    models.CharField(
                        blank=True,
                        help_text="Degrees and certifications (e.g., MD, MBBS, DO)",
                        max_length=250,
                    ),
                ),
                (
                    "default_test_priority",
                    models.CharField(
                        choices=[("routine", "Routine"), ("urgent", "Urgent")],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "enable_critical_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications for critical/panic values",
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("both", "Both")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("total_orders_placed", models.IntegerField(default=0)),
                ("last_order_date", models.DateTimeField(blank=True, null=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has admin verified clinician credentials?",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes on verification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Can this clinician place orders?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinician Profile",
                "verbose_name_plural": "Clinician Profiles",
            },
        ),
        migrations.CreateModel(
            name="ClinicianPatientRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Care Physician"),
                            ("specialist", "Specialist"),
                            ("consulting", "Consulting Physician"),
                            ("covering", "Covering Physician"),
                        ],
                        default="primary",
                        max_length=20,
                    ),
                ),
                ("can_order_tests", models.BooleanField(default=True)),
                ("can_view_results", models.BooleanField(default=True)),
                ("can_view_history", models.BooleanField(default=True)),
                ("established_date", models.DateTimeField(auto_now_add=True)),
                (
                    "established_via",
                    models.CharField(
                        blank=True,
                        help_text="How was relationship established? (e.g., 'First test order')",
                        max_length=100,
                    ),
                ),
                ("last_interaction", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this relationship currently active?"
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        limit_choices_to={"role": "clinician"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_relationships",
                        to="labs.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinician-Patient Relationship",
                "verbose_name_plural": "Clinician-Patient Relationships",
                "indexes": [
                    models.Index(
                        fields=["clinician", "is_active"],
                        name="clinician_c_clinici_5cb82a_idx",
                    ),
                    models.Index(
                        fields=["patient", "is_active"],
                        name="clinician_c_patient_1587fc_idx",
                    ),
                ],
                "unique_together": {("clinician", "patient")},
            },
        ),
    ]
