# Generated by Django 5.2.7 on 2026-02-19 10:42

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company Logo!",
                        null=True,
                        upload_to="logos/",
                    ),
                ),
                (
                    "director_signature",
                    models.ImageField(
                        blank=True,
                        help_text="Director's Signature",
                        null=True,
                        upload_to="signatures/",
                    ),
                ),
                (
                    "company_seal",
                    models.ImageField(
                        blank=True,
                        help_text="Company Seal",
                        null=True,
                        upload_to="seals/",
                    ),
                ),
                (
                    "office_address",
                    models.TextField(
                        blank=True, help_text="e.g. - 42, Awolowo Road, Old-Bodija"
                    ),
                ),
                (
                    "office_city_state",
                    models.CharField(
                        blank=True, help_text="Victoria-Island, Lagos", max_length=100
                    ),
                ),
                (
                    "office_country",
                    models.CharField(blank=True, help_text="Nigeria", max_length=100),
                ),
                (
                    "office_zipcode",
                    models.CharField(blank=True, help_text="200200", max_length=20),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="23.56",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="23.56",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, default="bank", max_length=11, null=True
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="bank", max_length=200, null=True
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True, default="bank", max_length=200, null=True
                    ),
                ),
                ("paystack_enabled", models.BooleanField(default=False)),
                (
                    "paystack_public_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paystack_secret_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("flutterwave_enabled", models.BooleanField(default=False)),
                (
                    "flutterwave_public_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "flutterwave_secret_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "require_payment_before_sample_verification",
                    models.BooleanField(default=True),
                ),
                ("allow_partial_payments", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "Platform Administrator"),
                            ("vendor_admin", "Lab Director / Super Admin"),
                            ("lab_manager", "Lab Manager / Supervisor"),
                            ("scientist", "Scientist / Pathologist / MLS"),
                            ("technologist", "Technologist / Phlebotomist"),
                            ("logistics", "Logistics Officer / Sample Collector"),
                            ("receptionist", "Receptionist / Front Desk"),
                            ("clinician", "Clinician"),
                            ("patient", "Patient"),
                            ("learner", "Learner"),
                            ("facilitator", "Facilitator"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "unique_together": {("email", "vendor")},
            },
        ),
    ]
