# Generated by Django 5.2.7 on 2025-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('vendor_admin', 'Vendor Admin'), ('lab_staff', 'Lab Staff'), ('clinician', 'Clinician'), ('patient', 'Patient'), ('learner', 'Learner'), ('facilitator', 'Facilitator')], default='lab_staff', max_length=32),
        ),
    ]
