# Generated by Django 5.2.7 on 2025-11-01 00:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_alter_vendor_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('vendor_admin', 'Vendor Admin'), ('lab_staff', 'Lab Staff'), ('clinician', 'Clinician'), ('patient', 'Patient')], default='lab_staff', max_length=32),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_img', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('office_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenants.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
