# Generated by Django 5.2.7 on 2025-11-12 13:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorprofile",
            name="contact_phone",
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
