# Generated by Django 5.2.7 on 2025-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Platform Admin"),
                    ("vendor_admin", "Vendor Admin"),
                    ("pathologist", "Pathologist"),
                    ("lab_supervisor", "Lab Supervisor"),
                    ("lab_technician", "Lab Technician"),
                    ("lab_manager", "Lab Manager"),
                    ("lab_staff", "Lab Staff"),
                    ("clinician", "Clinician"),
                    ("patient", "Patient"),
                    ("receptionist", "Receptionist"),
                    ("learner", "Learner"),
                    ("facilitator", "Facilitator"),
                ],
                default="lab_staff",
                max_length=32,
            ),
        ),
    ]
