# Generated by Django 5.2.7 on 2025-11-01 01:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_city_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='office_zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='office_address',
            field=models.TextField(blank=True, help_text='Number, street'),
        ),
    ]
