# Generated by Django 5.2.7 on 2026-01-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
        ("tenants", "0004_alter_vendordomain_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Platform Administrator"),
                    ("vendor_admin", "Lab Director / Super Admin"),
                    ("lab_manager", "Lab Manager / Supervisor"),
                    ("scientist", "Scientist / Pathologist / MLS"),
                    ("technologist", "Technologist / Phlebotomist"),
                    ("logistics", "Logistics Officer / Sample Collector"),
                    ("receptionist", "Receptionist / Front Desk"),
                    ("clinician", "Clinician"),
                    ("patient", "Patient"),
                    ("learner", "Learner"),
                    ("facilitator", "Facilitator"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.vendor",
            ),
        ),
    ]
