# Generated by Django 5.2.7 on 2026-01-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_alter_user_role_alter_user_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorprofile",
            name="allow_partial_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="bank_account",
            field=models.CharField(
                blank=True, default="bank", max_length=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="bank_account_name",
            field=models.CharField(
                blank=True, default="bank", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="bank_name",
            field=models.CharField(
                blank=True, default="bank", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="flutterwave_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="flutterwave_public_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="flutterwave_secret_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="paystack_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="paystack_public_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="paystack_secret_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="require_payment_before_sample_verification",
            field=models.BooleanField(default=True),
        ),
    ]
