
"""
═══════════════════════════════════════════════════════════════════════════════
REBATE SYSTEM — COMPLETE IMPLEMENTATION
═══════════════════════════════════════════════════════════════════════════════

File layout:
  billing/models/referrer.py          ← Referrer + RebateRecord models
  billing/signals.py                  ← auto-create RebateRecord on payment
  billing/views/rebate_views.py       ← statement view + settlement view
  billing/migrations/XXXX_referrer.py ← generated by makemigrations

Changes to existing models (minimal):
  BillingInformation  ← add referrer FK (nullable, SET_NULL)
                         add rebate_record reverse accessor (OneToOne on RebateRecord)

Nothing in labs/ is touched.
"""


# ─────────────────────────────────────────────────────────────────────────────
# FILE 1: billing/models/referrer.py
# ─────────────────────────────────────────────────────────────────────────────

"""
billing/models/referrer.py

Two new models:

  Referrer      — partner hospital / clinic / doctor
  RebateRecord  — immutable ledger entry created once per billing record
                  when a qualifying payment clears

Design decisions:

1.  RebateRecord is SEPARATE from BillingInformation.
    Storing rebate_earned as a plain field on BillingInformation would make
    it mutable and hard to audit. A separate ledger row:
      - Is created exactly once (OneToOneField prevents duplicates)
      - Has its own PAID/UNPAID status
      - Can be included in settlement batches
      - Survives if BillingInformation is edited later

2.  Rebate is calculated on `payment_basis` — the amount the lab actually
    collected for this record, not the contract price. This matches the
    business rule: "token is earned only after payment clears."

3.  RebateSettlement groups RebateRecords into a payment run. This lets the
    lab generate a statement, approve it, and mark it paid — mirroring the
    same Invoice → Payment flow used for HMO billing.
"""

import uuid
from decimal import Decimal as D, ROUND_HALF_UP

from django.conf import settings
from django.db import models
from django.utils import timezone


class Referrer(models.Model):
    REBATE_TYPE_CHOICES = [
        ('PERCENTAGE', 'Percentage of Amount Collected'),
        ('FIXED',      'Fixed Amount per Request'),
    ]

    id     = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vendor = models.ForeignKey(
        'tenants.Vendor', on_delete=models.CASCADE,
        related_name='referrers'
    )

    # ── Identity ──────────────────────────────────────────────────────────
    name           = models.CharField(max_length=255)
    code           = models.CharField(max_length=50, blank=True,
                                      help_text="Short internal code e.g. GHC, RHA")
    contact_person = models.CharField(max_length=100, blank=True)
    phone          = models.CharField(max_length=20, blank=True, null=True)
    email          = models.EmailField(blank=True)
    address        = models.TextField(blank=True)

    # ── Rebate agreement ──────────────────────────────────────────────────
    rebate_type = models.CharField(
        max_length=20, choices=REBATE_TYPE_CHOICES, default='PERCENTAGE',
    )
    rebate_value = models.DecimalField(
        max_digits=12, decimal_places=2, default=D('0.00'),
        help_text=(
            "10.00 = 10% of amount collected (PERCENTAGE), "
            "or ₦500.00 flat per request (FIXED)"
        )
    )

    # ── Payment details (for settlement) ─────────────────────────────────
    bank_name          = models.CharField(max_length=100, blank=True)
    account_number     = models.CharField(max_length=20, blank=True)
    account_name       = models.CharField(max_length=200, blank=True)
    payment_terms_days = models.IntegerField(
        default=30, help_text="Days after statement date when payment is due"
    )

    is_active  = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('vendor', 'code')
        ordering        = ['name']
        indexes         = [models.Index(fields=['vendor', 'is_active'])]

    def __str__(self):
        return f"{self.name} ({self.code or self.get_rebate_type_display()})"

    # ── Core calculation ──────────────────────────────────────────────────

    def calculate_rebate(self, payment_basis: D) -> D:
        """
        Calculate the rebate earned for a given payment_basis amount.

        payment_basis = the amount the lab actually collected for one
        billing record (patient_amount_paid + insurance_amount_paid).

        Always rounds to 2 decimal places using ROUND_HALF_UP.
        Returns 0 if the referrer or value is inactive / zero.
        """
        if not self.is_active or self.rebate_value <= 0 or payment_basis <= 0:
            return D('0.00')

        if self.rebate_type == 'PERCENTAGE':
            raw = payment_basis * (self.rebate_value / D('100'))
        else:
            raw = self.rebate_value

        return raw.quantize(D('0.01'), rounding=ROUND_HALF_UP)

    # ── Reporting helpers ─────────────────────────────────────────────────

    def get_unpaid_balance(self) -> D:
        """Total rebate owed to this referrer (unpaid RebateRecords)."""
        from django.db.models import Sum
        result = self.rebate_records.filter(
            status='UNPAID'
        ).aggregate(total=Sum('rebate_amount'))
        return D(result['total'] or 0).quantize(D('0.01'))

    def get_lifetime_earned(self) -> D:
        """Total rebate ever earned (all statuses)."""
        from django.db.models import Sum
        result = self.rebate_records.aggregate(total=Sum('rebate_amount'))
        return D(result['total'] or 0).quantize(D('0.01'))


# ─────────────────────────────────────────────────────────────────────────────

class RebateRecord(models.Model):
    """
    Immutable ledger entry: one row per billing record that earned a rebate.

    Created automatically by a signal when a billing record's payment
    clears (is_payment_cleared == True). Never modified after creation
    except for status transitions: UNPAID → PAID (when settled).

    OneToOneField on billing prevents duplicate rebate records.
    """

    STATUS_CHOICES = [
        ('UNPAID',   'Unpaid — Pending Settlement'),
        ('INCLUDED', 'Included in a Statement'),
        ('PAID',     'Paid — Settlement Complete'),
    ]

    id       = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    referrer = models.ForeignKey(
        Referrer, on_delete=models.PROTECT,
        related_name='rebate_records',
        help_text="Partner hospital this rebate is owed to"
    )
    billing  = models.OneToOneField(
        'billing.BillingInformation',
        on_delete=models.PROTECT,
        related_name='rebate_record',
        help_text="The billing record that generated this rebate"
    )
    settlement = models.ForeignKey(
        'billing.RebateSettlement',
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='rebate_records',
        help_text="The settlement batch this was paid in (null until settled)"
    )

    # ── Financial ─────────────────────────────────────────────────────────
    payment_basis  = models.DecimalField(
        max_digits=14, decimal_places=2,
        help_text="Amount collected from patient + insurance at calculation time"
    )
    rebate_amount  = models.DecimalField(
        max_digits=12, decimal_places=2,
        help_text="Actual rebate earned (calculated, then frozen)"
    )
    rebate_type    = models.CharField(max_length=20)   # snapshot of agreement at time
    rebate_value   = models.DecimalField(max_digits=12, decimal_places=2)  # snapshot

    status     = models.CharField(max_length=20, choices=STATUS_CHOICES, default='UNPAID')
    earned_at  = models.DateTimeField(default=timezone.now,
                                      help_text="When payment cleared and rebate was earned")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-earned_at']
        indexes  = [
            models.Index(fields=['referrer', 'status']),
            models.Index(fields=['earned_at']),
        ]

    def __str__(self):
        return (
            f"Rebate ₦{self.rebate_amount} → {self.referrer.name} "
            f"[{self.billing_id}] ({self.status})"
        )


# ─────────────────────────────────────────────────────────────────────────────

class RebateSettlement(models.Model):
    """
    A settlement batch: groups unpaid RebateRecords into a single payment run.

    Mirrors the Invoice model structure so the workflow is familiar:
      DRAFT → APPROVED → PAID → (CANCELLED)

    The lab creates a statement (DRAFT), reviews it, approves it, then records
    the bank transfer to the referrer and marks it PAID.
    """

    STATUS_CHOICES = [
        ('DRAFT',     'Draft'),
        ('APPROVED',  'Approved — Awaiting Payment'),
        ('PAID',      'Paid'),
        ('CANCELLED', 'Cancelled'),
    ]

    id       = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vendor   = models.ForeignKey(
        'tenants.Vendor', on_delete=models.CASCADE,
        related_name='rebate_settlements'
    )
    referrer = models.ForeignKey(
        Referrer, on_delete=models.PROTECT,
        related_name='settlements'
    )

    statement_number = models.CharField(max_length=50, unique=True)
    period_start     = models.DateField()
    period_end       = models.DateField()

    total_amount = models.DecimalField(
        max_digits=14, decimal_places=2, default=D('0.00'),
        help_text="Sum of all RebateRecord.rebate_amount in this batch"
    )
    record_count = models.IntegerField(default=0)

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='DRAFT')

    # Payment proof (filled in when PAID)
    payment_date      = models.DateField(null=True, blank=True)
    payment_reference = models.CharField(max_length=100, blank=True)
    payment_method    = models.CharField(max_length=50, blank=True)

    notes      = models.TextField(blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.statement_number} — {self.referrer.name} — ₦{self.total_amount}"

    def recalculate_totals(self):
        """Recompute total_amount and record_count from attached RebateRecords."""
        from django.db.models import Sum, Count
        agg = self.rebate_records.aggregate(
            total=Sum('rebate_amount'),
            count=Count('id'),
        )
        self.total_amount = D(agg['total'] or 0).quantize(D('0.01'))
        self.record_count = agg['count'] or 0
        self.save(update_fields=['total_amount', 'record_count', 'updated_at'])


# ─────────────────────────────────────────────────────────────────────────────
# FILE 2: billing/models/billing_information.py  (ADDITIONS ONLY)
# ─────────────────────────────────────────────────────────────────────────────

"""
Add these two things to your existing BillingInformation model.
Do NOT rewrite the model — just add the FK and the method.

Migration will be:
  python manage.py makemigrations billing --name add_referrer_to_billing
"""

# ── Add this field to BillingInformation ─────────────────────────────────────
#
# referrer = models.ForeignKey(
#     'billing.Referrer',
#     on_delete=models.SET_NULL,
#     null=True, blank=True,
#     related_name='billing_records',
#     help_text="Referring hospital/clinic that brought this patient"
# )
#
# ── Add this method to BillingInformation ────────────────────────────────────

def calculate_and_create_rebate(self) -> 'RebateRecord | None':
    """
    Calculate and persist a RebateRecord for this billing entry.

    Rules:
      1. Must have a referrer set.
      2. Payment must have cleared (is_payment_cleared == True).
      3. A RebateRecord must not already exist for this billing
         (OneToOneField prevents duplicates, but we check first for
          a clean error message rather than relying on IntegrityError).
      4. Rebate basis = patient_amount_paid + insurance_amount_paid
         (what the lab actually received, not the contract price).

    Returns the created RebateRecord, or None if conditions not met.
    Called by a post_save signal on Payment and InvoicePayment.
    """
    from billing.models.referrer import RebateRecord  # avoid circular import

    if not self.referrer_id:
        return None

    if not self.is_payment_cleared:
        return None

    # Idempotency guard — never double-create
    if hasattr(self, 'rebate_record') and self.rebate_record is not None:
        return self.rebate_record

    try:
        _ = self.rebate_record  # raises RelatedObjectDoesNotExist if none
        return self.rebate_record
    except Exception:
        pass  # no existing record — proceed

    payment_basis = (
        D(self.patient_amount_paid or 0) +
        D(self.insurance_amount_paid or 0)
    )

    rebate_amount = self.referrer.calculate_rebate(payment_basis)

    if rebate_amount <= 0:
        return None

    return RebateRecord.objects.create(
        referrer      = self.referrer,
        billing       = self,
        payment_basis = payment_basis,
        rebate_amount = rebate_amount,
        rebate_type   = self.referrer.rebate_type,
        rebate_value  = self.referrer.rebate_value,
        status        = 'UNPAID',
    )


# ─────────────────────────────────────────────────────────────────────────────
# FILE 3: billing/signals.py  (ADD TO EXISTING FILE)
# ─────────────────────────────────────────────────────────────────────────────

"""
billing/signals.py

Trigger rebate calculation automatically when:
  a) A Payment is saved (patient front-desk payment)
  b) An InvoicePayment is saved (HMO/insurance payment)

Both signal handlers check is_payment_cleared after the save,
so the rebate is only created once all conditions are met.
"""

import logging
from django.db.models.signals import post_save
from django.dispatch import receiver

logger = logging.getLogger(__name__)


# Triggered when a patient Payment is recorded at the front desk
# @receiver(post_save, sender='billing.Payment')
# def create_rebate_on_patient_payment(sender, instance, created, **kwargs):
#     billing = instance.billing
#     if billing.referrer_id and billing.is_payment_cleared:
#         try:
#             record = billing.calculate_and_create_rebate()
#             if record:
#                 logger.info(
#                     "Rebate ₦%s created for billing %s → referrer %s",
#                     record.rebate_amount, billing.pk, billing.referrer.name,
#                 )
#         except Exception:
#             logger.exception(
#                 "Failed to create rebate record for billing %s", billing.pk
#             )


# Triggered when an InvoicePayment propagates back to billing records
# The propagation in InvoicePayment._propagate_to_billing_records() updates
# insurance_amount_paid, but does not call save() signals on BillingInformation.
# So we hook into InvoicePayment.save() instead.
#
# @receiver(post_save, sender='billing.InvoicePayment')
# def create_rebate_on_insurance_payment(sender, instance, created, **kwargs):
#     invoice = instance.invoice
#     for billing in invoice.billing_records.filter(referrer__isnull=False):
#         if billing.is_payment_cleared:
#             try:
#                 record = billing.calculate_and_create_rebate()
#                 if record:
#                     logger.info(
#                         "Rebate ₦%s created for billing %s → referrer %s",
#                         record.rebate_amount, billing.pk, billing.referrer.name,
#                     )
#             except Exception:
#                 logger.exception(
#                     "Failed to create rebate for billing %s on invoice %s",
#                     billing.pk, invoice.pk,
#                 )


# ── HOW TO ACTIVATE ───────────────────────────────────────────────────────────
# Uncomment the decorators above and ensure billing/apps.py has:
#
# class BillingConfig(AppConfig):
#     name = 'billing'
#     def ready(self):
#         import billing.signals  # noqa: F401


# ─────────────────────────────────────────────────────────────────────────────
# FILE 4: billing/views/rebate_views.py
# ─────────────────────────────────────────────────────────────────────────────

"""
billing/views/rebate_views.py

Views:
  rebate_statement_view      — filter by referrer + date range, show aggregated records
  generate_settlement_view   — POST: create a RebateSettlement from selected records
  settlement_detail_view     — view a settlement, mark it APPROVED or PAID
  referrer_list_view         — CRUD list of partner hospitals

URL names:
  billing:rebate_statement
  billing:generate_settlement
  billing:settlement_detail    <uuid:pk>
  billing:referrer_list
  billing:referrer_create
"""

import logging
from datetime import date
from decimal import Decimal as D

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count, Sum
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

logger = logging.getLogger(__name__)


def _generate_statement_number(vendor, referrer) -> str:
    """RBS-{CODE}-{YEAR}-{SEQ:04d}  e.g. RBS-GHC-2026-0003"""
    from billing.models.referrer import RebateSettlement
    year = timezone.now().year
    prefix = f"RBS-{referrer.code or referrer.name[:4].upper()}-{year}-"
    last = (
        RebateSettlement.objects
        .select_for_update()
        .filter(vendor=vendor, statement_number__startswith=prefix)
        .order_by('-statement_number')
        .first()
    )
    seq = 1
    if last:
        try:
            seq = int(last.statement_number.rsplit('-', 1)[-1]) + 1
        except (ValueError, IndexError):
            pass
    return f"{prefix}{seq:04d}"


@login_required
def rebate_statement_view(request):
    """
    Statement engine: filter unpaid RebateRecords by referrer + date range.

    GET  → show filter form + preview of unpaid records
    POST → create a RebateSettlement from selected records
    """
    from billing.models.referrer import Referrer, RebateRecord, RebateSettlement

    vendor = getattr(request.user, 'vendor', None)
    if not vendor:
        messages.error(request, "Vendor account required.")
        return redirect('dashboard')

    # ── GET: filter + preview ─────────────────────────────────────────────
    if request.method == 'GET':
        referrers   = Referrer.objects.filter(vendor=vendor, is_active=True)
        referrer_id = request.GET.get('referrer', '').strip()
        start_str   = request.GET.get('start', '').strip()
        end_str     = request.GET.get('end', '').strip()

        records          = RebateRecord.objects.none()
        selected_referrer = None
        summary          = None
        start_date = end_date = None

        if referrer_id and start_str and end_str:
            try:
                start_date = date.fromisoformat(start_str)
                end_date   = date.fromisoformat(end_str)
            except ValueError:
                messages.error(request, "Invalid date format. Use YYYY-MM-DD.")
                return render(request, 'billing/rebate/statement.html', {
                    'referrers': referrers,
                })

            selected_referrer = get_object_or_404(
                Referrer, pk=referrer_id, vendor=vendor
            )

            records = (
                RebateRecord.objects
                .filter(
                    referrer=selected_referrer,
                    status='UNPAID',
                    earned_at__date__range=[start_date, end_date],
                )
                .select_related(
                    'billing',
                    'billing__request',
                    'billing__request__patient',
                )
                .order_by('earned_at')
            )

            agg = records.aggregate(
                total=Sum('rebate_amount'),
                count=Count('id'),
                basis_total=Sum('payment_basis'),
            )
            summary = {
                'record_count':  agg['count']       or 0,
                'total_rebate':  D(agg['total']      or 0),
                'total_basis':   D(agg['basis_total'] or 0),
            }

            if not records.exists():
                messages.info(
                    request,
                    f"No unpaid rebates found for {selected_referrer.name} "
                    f"in the selected period."
                )

        # Balance summary for all referrers (sidebar)
        referrer_balances = (
            Referrer.objects
            .filter(vendor=vendor, is_active=True)
            .annotate(
                unpaid_total=Sum(
                    'rebate_records__rebate_amount',
                    filter=models.Q(rebate_records__status='UNPAID')
                )
            )
        )

        return render(request, 'billing/rebate/statement.html', {
            'referrers':          referrers,
            'referrer_balances':  referrer_balances,
            'records':            records,
            'selected_referrer':  selected_referrer,
            'summary':            summary,
            'start':              start_str,
            'end':                end_str,
        })

    # ── POST: generate settlement ─────────────────────────────────────────
    if request.method == 'POST':
        from billing.models.referrer import Referrer, RebateRecord, RebateSettlement

        record_ids  = request.POST.getlist('record_ids')
        referrer_id = request.POST.get('referrer_id')
        start_str   = request.POST.get('start')
        end_str     = request.POST.get('end')

        if not record_ids:
            messages.error(request, "No records selected.")
            return redirect('billing:rebate_statement')

        referrer = get_object_or_404(Referrer, pk=referrer_id, vendor=vendor)

        try:
            with transaction.atomic():
                stmt_number = _generate_statement_number(vendor, referrer)

                settlement = RebateSettlement.objects.create(
                    vendor           = vendor,
                    referrer         = referrer,
                    statement_number = stmt_number,
                    period_start     = start_str,
                    period_end       = end_str,
                    created_by       = request.user,
                    status           = 'DRAFT',
                )

                # Attach records — re-validate eligibility in the same transaction
                eligible = RebateRecord.objects.filter(
                    id__in=record_ids,
                    referrer=referrer,
                    status='UNPAID',
                )
                if not eligible.exists():
                    raise ValueError("No eligible unpaid records found.")

                eligible.update(status='INCLUDED', settlement=settlement)
                settlement.recalculate_totals()

            messages.success(
                request,
                f"Statement {stmt_number} created for {referrer.name} "
                f"— ₦{settlement.total_amount:,.2f} across "
                f"{settlement.record_count} records."
            )
            return redirect('billing:settlement_detail', pk=settlement.pk)

        except ValueError as e:
            messages.error(request, str(e))
        except Exception:
            logger.exception("Settlement generation failed")
            messages.error(request, "An unexpected error occurred. Please try again.")

        return redirect('billing:rebate_statement')


@login_required
def settlement_detail_view(request, pk):
    """
    View a RebateSettlement.
    POST actions: approve, mark_paid, cancel.
    """
    from billing.models.referrer import RebateSettlement

    vendor = getattr(request.user, 'vendor', None)
    if not vendor:
        return redirect('dashboard')

    settlement = get_object_or_404(
        RebateSettlement.objects.select_related('referrer', 'created_by'),
        pk=pk, vendor=vendor,
    )
    records = settlement.rebate_records.select_related(
        'billing', 'billing__request', 'billing__request__patient'
    ).order_by('earned_at')

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'approve' and settlement.status == 'DRAFT':
            settlement.status = 'APPROVED'
            settlement.save(update_fields=['status', 'updated_at'])
            messages.success(request, f"Statement {settlement.statement_number} approved.")

        elif action == 'mark_paid' and settlement.status == 'APPROVED':
            payment_ref    = request.POST.get('payment_reference', '').strip()
            payment_method = request.POST.get('payment_method', '').strip()
            payment_date_str = request.POST.get('payment_date', '').strip()

            if not payment_ref:
                messages.error(request, "Payment reference is required.")
            else:
                try:
                    with transaction.atomic():
                        p_date = (
                            date.fromisoformat(payment_date_str)
                            if payment_date_str else timezone.now().date()
                        )
                        settlement.status           = 'PAID'
                        settlement.payment_date     = p_date
                        settlement.payment_reference = payment_ref
                        settlement.payment_method   = payment_method
                        settlement.save(update_fields=[
                            'status', 'payment_date', 'payment_reference',
                            'payment_method', 'updated_at'
                        ])
                        settlement.rebate_records.update(status='PAID')

                    messages.success(
                        request,
                        f"Settlement {settlement.statement_number} marked as PAID. "
                        f"₦{settlement.total_amount:,.2f} disbursed to {settlement.referrer.name}."
                    )
                except Exception:
                    logger.exception("Failed to mark settlement %s as paid", pk)
                    messages.error(request, "Could not record payment. Please try again.")

        elif action == 'cancel' and settlement.status in ('DRAFT', 'APPROVED'):
            with transaction.atomic():
                settlement.rebate_records.update(status='UNPAID', settlement=None)
                settlement.status = 'CANCELLED'
                settlement.save(update_fields=['status', 'updated_at'])
            messages.warning(
                request,
                f"Statement {settlement.statement_number} cancelled. "
                f"Records returned to unpaid pool."
            )

        return redirect('billing:settlement_detail', pk=pk)

    context = {
        'settlement': settlement,
        'referrer':   settlement.referrer,
        'records':    records,
        'can_approve': settlement.status == 'DRAFT',
        'can_pay':     settlement.status == 'APPROVED',
        'can_cancel':  settlement.status in ('DRAFT', 'APPROVED'),
    }
    return render(request, 'billing/rebate/settlement_detail.html', context)


@login_required
def referrer_list_view(request):
    """List all referrers with their unpaid balance summary."""
    from billing.models.referrer import Referrer
    from django.db.models import Q

    vendor = getattr(request.user, 'vendor', None)
    if not vendor:
        return redirect('dashboard')

    referrers = (
        Referrer.objects
        .filter(vendor=vendor)
        .annotate(
            unpaid_count=Count(
                'rebate_records',
                filter=Q(rebate_records__status='UNPAID')
            ),
            unpaid_total=Sum(
                'rebate_records__rebate_amount',
                filter=Q(rebate_records__status='UNPAID')
            ),
            lifetime_earned=Sum('rebate_records__rebate_amount'),
        )
        .order_by('name')
    )

    return render(request, 'billing/rebate/referrer_list.html', {
        'referrers': referrers,
    })


# ─────────────────────────────────────────────────────────────────────────────
# FILE 5: URL additions (billing/urls.py)
# ─────────────────────────────────────────────────────────────────────────────

"""
Add to billing/urls.py:

    # Referrer & Rebate
    path('referrers/',
         rebate_views.referrer_list_view,       name='referrer_list'),

    path('rebates/statement/',
         rebate_views.rebate_statement_view,    name='rebate_statement'),

    path('rebates/settlements/<uuid:pk>/',
         rebate_views.settlement_detail_view,   name='settlement_detail'),
"""


# ─────────────────────────────────────────────────────────────────────────────
# FILE 6: Migration steps
# ─────────────────────────────────────────────────────────────────────────────

"""
1. Add the new models to billing/models/__init__.py:
   from .referrer import Referrer, RebateRecord, RebateSettlement

2. Add the FK to BillingInformation:
   referrer = models.ForeignKey(
       'billing.Referrer', on_delete=models.SET_NULL,
       null=True, blank=True, related_name='billing_records'
   )

3. Run:
   python manage.py makemigrations billing --name add_referrer_rebate_system
   python manage.py migrate

4. Uncomment signal decorators in billing/signals.py

5. Ensure billing/apps.py imports signals:
   def ready(self):
       import billing.signals  # noqa: F401
"""


# ─────────────────────────────────────────────────────────────────────────────
# EXAMPLE: Manual rebate creation (for backfill or testing)
# ─────────────────────────────────────────────────────────────────────────────

"""
# In Django shell:

from billing.models import BillingInformation
from billing.models.referrer import Referrer

# Assign a referrer to an existing billing record
billing = BillingInformation.objects.get(pk='...')
referrer = Referrer.objects.get(code='GHC')
billing.referrer = referrer
billing.save(update_fields=['referrer'])

# Manually trigger rebate (normally done by signal)
record = billing.calculate_and_create_rebate()
print(record)
# → Rebate ₦450.00 → General Hospital Clinic [<uuid>] (UNPAID)
"""

