# Generated by Django 5.2.7 on 2026-02-19 10:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "bank_name",
                    models.CharField(blank=True, help_text="Bank name", max_length=100),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True, help_text="Internal account number", max_length=50
                    ),
                ),
                ("contact_person", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("billing_address", models.TextField()),
                (
                    "payment_terms_days",
                    models.IntegerField(default=60, help_text="Days until payment due"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "special_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Extra discount for corporate clients",
                        max_digits=5,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Corporate discount cap",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_clients",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., AVON HMO, Hygeia HMO", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Short code: AVON, HYG", max_length=20),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "payment_terms_days",
                    models.IntegerField(default=30, help_text="Days until payment due"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "patient_copay_percentage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.60"),
                        help_text="Patient co-pay percentage (0.60 = 60%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_preauth",
                    models.BooleanField(
                        default=False, help_text="Require pre-authorization for tests"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_providers",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BillingInformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash/Self-Pay"),
                            ("HMO", "HMO/Insurance"),
                            ("CORPORATE", "Corporate Account"),
                            ("NHIS", "NHIS (Government)"),
                            ("STAFF", "Staff (Internal)"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("policy_number", models.CharField(blank=True, max_length=100)),
                (
                    "pre_authorization_code",
                    models.CharField(blank=True, max_length=100),
                ),
                ("employee_id", models.CharField(blank=True, max_length=100)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "manual_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "waiver_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "patient_portion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "insurance_portion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "patient_amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "insurance_amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partially Paid"),
                            ("AUTHORIZED", "Authorized to Proceed"),
                            ("PAID", "Fully Paid"),
                            ("INVOICED", "Invoiced (Awaiting Payment)"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived/Written Off"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("billing_notes", models.TextField(blank=True)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("authorization_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_info",
                        to="labs.testrequest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "corporate_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.corporateclient",
                    ),
                ),
                (
                    "insurance_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_records",
                        to="billing.insuranceprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                ("due_date", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_records",
                    models.ManyToManyField(
                        related_name="invoices", to="billing.billinginformation"
                    ),
                ),
                (
                    "corporate_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.corporateclient",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insurance_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="billing.insuranceprovider",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("POS", "POS (Card)"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("MOBILE", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="POS ref, transfer ref, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="billing.billinginformation",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'AVON HMO Rates'", max_length=100
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("RETAIL", "Retail (Cash Patients)"),
                            ("HMO", "HMO/Insurance"),
                            ("CORPORATE", "Corporate Account"),
                            ("NHIS", "NHIS (Government)"),
                            ("STAFF", "Staff Discount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, help_text="HMO name or company name", max_length=200
                    ),
                ),
                ("contract_number", models.CharField(blank=True, max_length=100)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overall discount on retail prices",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax % applied AFTER discounts (e.g., 7.5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount allowed (e.g., ₦2000 max off)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "allow_overrides",
                    models.BooleanField(
                        default=False,
                        help_text="Permit staff to override discount rules",
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["price_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="insuranceprovider",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.pricelist",
            ),
        ),
        migrations.AddField(
            model_name="corporateclient",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.pricelist",
            ),
        ),
        migrations.AddField(
            model_name="billinginformation",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Which price list was applied",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.pricelist",
            ),
        ),
        migrations.CreateModel(
            name="TestPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for this test in this price list",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage discount for this specific test",
                        max_digits=5,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lab's cost to perform this test",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_prices",
                        to="billing.pricelist",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="labs.vendortest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["vendor", "status"], name="billing_inv_vendor__538a9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="billing_inv_due_dat_e51895_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricelist",
            unique_together={("vendor", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="insuranceprovider",
            unique_together={("vendor", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="corporateclient",
            unique_together={("vendor", "bank_account_number")},
        ),
        migrations.AddIndex(
            model_name="billinginformation",
            index=models.Index(
                fields=["vendor", "billing_type"], name="billing_bil_vendor__abbe3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billinginformation",
            index=models.Index(
                fields=["payment_status"], name="billing_bil_payment_150e9d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testprice",
            unique_together={("price_list", "test")},
        ),
    ]
