# Generated by Django 5.2.7 on 2026-02-20 14:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("labs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="corporateclient",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="corporateclient",
            name="price_list",
        ),
        migrations.RemoveField(
            model_name="corporateclient",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="corporate_client",
        ),
        migrations.RemoveField(
            model_name="billinginformation",
            name="corporate_client",
        ),
        migrations.RemoveField(
            model_name="pricelist",
            name="max_discount_amount",
        ),
        migrations.AddField(
            model_name="insuranceprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("HMO", "HMO / Private Insurance"),
                    ("NHIS", "NHIS (Government)"),
                    ("CORPORATE", "Corporate / Wellness"),
                    ("STAFF", "Staff (Internal)"),
                ],
                default="HMO",
                help_text="Category of payer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="insuranceprovider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash / Self-Pay"),
                    ("HMO", "HMO / Insurance"),
                    ("CORPORATE", "Corporate / Wellness"),
                    ("NHIS", "NHIS (Government)"),
                    ("STAFF", "Staff (Internal)"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total negotiated discount applied",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="employee_id",
            field=models.CharField(
                blank=True,
                help_text="Staff / corporate employee ID if applicable",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="insurance_portion",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount invoiced to the payer later",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="manual_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Manual flat-amount discount applied by staff (reduces total before co-pay split)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="patient_portion",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount patient pays at the front desk",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PARTIAL", "Partially Paid"),
                    ("AUTHORIZED", "Authorized to Proceed"),
                    ("PAID", "Fully Paid"),
                    ("INVOICED", "Invoiced (Awaiting Payment)"),
                    ("OVERDUE", "Overdue"),
                    ("WAIVED", "Waived / Written Off"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Price list snapshotted at request creation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.pricelist",
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of retail test prices before any discount",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final Contract Price (subtotal − discount + tax)",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="waiver_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Waiver/write-off amount (reduces patient portion post-split)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="insuranceprovider",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="0 = unlimited credit",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="insuranceprovider",
            name="name",
            field=models.CharField(
                help_text="e.g. AVON HMO, Hygeia HMO", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="insuranceprovider",
            name="patient_copay_percentage",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.6000"),
                help_text="Fraction of the Final Contract Price the patient pays at the front desk. 0.6000 = 60% patient / 40% HMO. Use 1.0000 for full patient responsibility (cash-equivalent). Use 0.0000 for full HMO coverage.",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="insuranceprovider",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Negotiated rate price list for this provider",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.pricelist",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of insurance_portion across all attached billing records",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Negotiated rate discount on retail prices (e.g. 10 = 10%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="name",
            field=models.CharField(help_text="e.g. 'Ajinks HMO Rates'", max_length=100),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("RETAIL", "Retail (Cash Patients)"),
                    ("HMO", "HMO/Insurance"),
                    ("CORPORATE", "Corporate / Wellness"),
                    ("NHIS", "NHIS (Government)"),
                    ("STAFF", "Staff Discount"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="tax_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax % applied after discount (e.g. 7.5)",
                max_digits=5,
            ),
        ),
        migrations.AddIndex(
            model_name="billinginformation",
            index=models.Index(
                fields=["vendor", "insurance_provider"],
                name="billing_bil_vendor__2ddb10_idx",
            ),
        ),
        migrations.DeleteModel(
            name="CorporateClient",
        ),
    ]
