# Generated by Django 5.2.7 on 2026-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_corporateclient_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("RETAIL", "Retail"),
                    ("HMO", "HMO/Insurance"),
                    ("CORPORATE", "Corporate / Wellness"),
                    ("NHIS", "NHIS (Government)"),
                    ("STAFF", "Staff Discount"),
                ],
                max_length=20,
            ),
        ),
    ]
