# Generated by Django 5.2.7 on 2026-02-23 01:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_pricelist_price_type"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referrer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short internal code e.g. GHC, RHA",
                        max_length=50,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "rebate_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage of Amount Collected"),
                            ("FIXED", "Fixed Amount per Request"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "rebate_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="10.00 = 10% of amount collected (PERCENTAGE), or ₦500.00 flat per request (FIXED)",
                        max_digits=12,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("account_number", models.CharField(blank=True, max_length=20)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                (
                    "payment_terms_days",
                    models.IntegerField(
                        default=30,
                        help_text="Days after statement date when payment is due",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrers",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RebateSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement_number", models.CharField(max_length=50, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all RebateRecord.rebate_amount in this batch",
                        max_digits=14,
                    ),
                ),
                ("record_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved — Awaiting Payment"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebate_settlements",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="billing.referrer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RebateRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_basis",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount collected from patient + insurance at calculation time",
                        max_digits=14,
                    ),
                ),
                (
                    "rebate_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual rebate earned (calculated, then frozen)",
                        max_digits=12,
                    ),
                ),
                ("rebate_type", models.CharField(max_length=20)),
                ("rebate_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid — Pending Settlement"),
                            ("INCLUDED", "Included in a Statement"),
                            ("PAID", "Paid — Settlement Complete"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When payment cleared and rebate was earned",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing",
                    models.OneToOneField(
                        help_text="The billing record that generated this rebate",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebate_record",
                        to="billing.billinginformation",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        help_text="The settlement batch this was paid in (null until settled)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rebate_records",
                        to="billing.rebatesettlement",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        help_text="Partner hospital this rebate is owed to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebate_records",
                        to="billing.referrer",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
            },
        ),
        migrations.AddIndex(
            model_name="referrer",
            index=models.Index(
                fields=["vendor", "is_active"], name="billing_ref_vendor__076e36_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referrer",
            unique_together={("vendor", "code")},
        ),
        migrations.AddIndex(
            model_name="rebaterecord",
            index=models.Index(
                fields=["referrer", "status"], name="billing_reb_referre_4edbe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rebaterecord",
            index=models.Index(
                fields=["earned_at"], name="billing_reb_earned__d75dd2_idx"
            ),
        ),
    ]
