# Generated by Django 5.2.7 on 2026-02-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_referrer_rebatesettlement_rebaterecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billinginformation",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_records",
                to="billing.referrer",
            ),
        ),
    ]
