# Generated by Django 5.2.7 on 2026-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billinginformation_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('AUTHORIZED', 'Authorized to Proceed'), ('PAID', 'Fully Paid'), ('INVOICED', 'Invoiced'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived / Written Off')], default='UNPAID', max_length=20),
        ),
    ]
