"""
Django settings for lims_auth project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = False  # overridden in dev.py

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",    
    "django.contrib.staticfiles",   # to be also used with the django degug toolbar

    # created apps 
    "apps.accounts",
    "apps.tenants",
    "apps.core",
    "apps.labs", # manages CRM and lab operations
    "apps.inventory",
    "apps.billing",
    "apps.lms", # Learning Management System

    # installed apps 
    'phonenumber_field',

    # styling 
    'tailwind',
    'theme',
    'django_browser_reload',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
]

TAILWIND_APP_NAME = "theme"

MIGRATION_MODULES = {
    "debug_toolbar": None,
}

INTERNAL_IPS = [
    "127.0.0.1",
    'localhost',
]

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.core.middleware.TenantMiddleware", # created middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware", # tailwind
    "whitenoise.middleware.WhiteNoiseMiddleware", # Whitenoise
]

ROOT_URLCONF = "lims_auth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # "DIRS": [BASE_DIR / "templates"],
        "DIRS": [BASE_DIR / "templates_"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.accounts.context_processors.vendor_context",
            ],
        },
    },
]

WSGI_APPLICATION = "lims_auth.wsgi.application"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'

# gmail settings
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
PLATFORM_ADMIN_EMAIL = os.getenv("PLATFORM_ADMIN_EMAIL")
SITE_NAME = "mednovu.com"

# set production 
if ENVIRONMENT == "production":
    DEBUG = False

    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }

    GLOBAL_HOSTS = [os.getenv("PLATFORM_BASE_DOMAIN", "firstjplims.com")]
else:

    DEBUG = True

    INSTALLED_APPS += ["debug_toolbar"]

    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

    INTERNAL_IPS = ["127.0.0.1"]

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


    PLATFORM_BASE_DOMAIN = "localhost.test"  # Used for domain generation
    GLOBAL_HOSTS = [
        "127.0.0.1",
        "localhost",
        ".localhost.test",
    ]

    ALLOWED_HOSTS = GLOBAL_HOSTS


