"""
Django settings for lims_auth project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url

load_dotenv()

ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
ENVIRONMENT = "production" 

# BASE_DIR = Path(__file__).resolve().parent.parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = True  # Default to False for safety

# Base installed apps (always included)
INSTALLED_APPS = [
    # "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",    
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # for Data 

    # created apps 
    "apps.accounts",
    "apps.tenants",
    "apps.patient",
    "apps.clinician",
    "apps.core",
    "apps.labs",
    "apps.inventory",
    "apps.billing",
    "apps.doc_control",
    "apps.appointment",
    "apps.notification",
    "apps.learn",

    # installed apps 
    'phonenumber_field',
    "channels",

    # styling 
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
]

# Channels 
ASGI_APPLICATION = 'lims_auth.asgi.application'

# 6379

MIGRATION_MODULES = {
    "debug_toolbar": None,
}

INTERNAL_IPS = [
    "127.0.0.1",
    'localhost',
]


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'accounts.User'

# Base middleware (always included)
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "apps.core.middleware.TenantMiddleware", # Tenant middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


AUTHENTICATION_BACKENDS = [
    'apps.accounts.backend.VendorEmailBackend',   # tenant-aware
    # 'django.contrib.auth.backends.ModelBackend',  # fallback
]


LOGIN_URL = 'account:login'
LOGOUT_REDIRECT_URL = 'account:login'


ROOT_URLCONF = "lims_auth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.accounts.context_processors.vendor_context",  # vendor attributes
                "apps.tenants.context_processors.vendor_context",  # vendor attributes
                "apps.core.context_processors.platform_urls",  # platform URLs
                # 'apps.notification.context_processors.notifications', 
            ],
        },
    },
]

WSGI_APPLICATION = "lims_auth.wsgi.application"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email setting - Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
DEFAULT_FROM_EMAIL = os.getenv("PLATFORM_ADMIN_EMAIL")
SERVER_EMAIL = DEFAULT_FROM_EMAIL



# Using MailTrap Sandbox for email testing
# Looking to send emails in production? Check out our Email API/SMTP product!
# EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
# EMAIL_HOST_USER = '29d1b943562a3e'
# EMAIL_HOST_PASSWORD = 'b5ad38fa222492'
# EMAIL_PORT = '2525'


SITE_NAME = "medvuno.com"

PLATFORM_ADMIN_EMAIL = "medvuno@gmail.com"

# STATIC_ROOT = BASE_DIR / "staticfiles"

# SMS
PHONENUMBER_DEFAULT_REGION = "NG"

# ========================================
# ENVIRONMENT-SPECIFIC SETTINGS
# ========================================

if ENVIRONMENT == "production":
    # Production settings
    # DEBUG = False
    DEBUG = True

    INSTALLED_APPS += [
        "storages",
    ]

    # 2. Add this if you are using whitenoise to serve the compiled css
    # This helps Django find the manifest file
    WHITENOISE_MANIFEST_STRICT = False

    ALLOWED_HOSTS = [
        "medvuno.com",
        "www.medvuno.com",
        ".medvuno.com",
        '13.63.45.144',
        'localhost', '127.0.0.1'
    ]

    PLATFORM_BASE_DOMAIN = "medvuno.com"
    LEARN_BASE_URL = f"https://learn.{PLATFORM_BASE_DOMAIN}"
    
    # CSRF trusted origins for production
    CSRF_TRUSTED_ORIGINS = [
        # "https://firstjp-lims-web-ytsi.onrender.com",
        "https://medvuno.com",
        "https://www.medvuno.com",
    ]

    GLOBAL_HOSTS = [
        PLATFORM_BASE_DOMAIN,
        f"www.{PLATFORM_BASE_DOMAIN}",
        f"{LEARN_BASE_URL}",
    ]
    
    DATABASES = {
        'default': dj_database_url.parse(os.getenv("DATABASE_URL")),
    }
    

    STATIC_URL = "/static/"
    STATICFILES_DIRS = [BASE_DIR / "static"]
    STATIC_ROOT = BASE_DIR / "staticfiles"

    # STORAGES = {
    #     "default": {
    #         "BACKEND": "storages.backends.s3.S3Storage",
    #         "OPTIONS": {
    #         # ...your_options_here
    #         },
    #     },
    # }

    # Redis server - RENDER
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [(os.getenv('RENDER_INTERNAL_REDIS_URL'), 6379)],  # Production Redis endpoint
            },
        },
    }

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('RENDER_INTERNAL_REDIS_URL2'),  # Same server, database 1
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        },
    }

 
    # Security settings for production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    # Development settings
    DEBUG = True
    
    # NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd" # Replaced with nodejs tailwind

    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
        ".localhost.test",
    ]
    
    DATABASES = {
        # iyanudb12345
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    

    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.postgresql',
    #         'NAME': 'medvuno-local-db',
    #         'USER': 'postgres',
    #         'PASSWORD': 'iyanudb12345',
    #         'HOST': 'localhost',
    #         'PORT': '5432',
    #     }
    # }


    PLATFORM_BASE_DOMAIN = "localhost.test"
    LEARN_BASE_URL = "http://learn.localhost.test:8000"

    GLOBAL_HOSTS = [
        "127.0.0.1",
        "localhost",
        ".localhost.test",
        "learn.localhost.test"
    ]
    
    # Development-only apps
    INSTALLED_APPS += [
        "debug_toolbar",
        "django_browser_reload",
    ]
    
    # Add development-only middleware
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]
    
    # INTERNAL_IPS = ["127.0.0.1"]
    # Static files
    # STATIC_URL = '/static/'
    # STATICFILES_DIRS = [BASE_DIR / "static"]
    # STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

    STATIC_URL = "/static/"
    STATICFILES_DIRS = [BASE_DIR / "static"]
    STATIC_ROOT = BASE_DIR / "staticfiles"


    # Media files
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [('127.0.0.1', 6379)],
            },
        },
    }

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION':'redis://127.0.0.1:6379/1',
            'OPTIONS': {
                'CLIENT_CLASS':'django_redis.client.DefaultClient',
            },
        },
    }


