# Generated by Django 5.2.7 on 2025-10-30 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tenant_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('subdomain_prefix', models.SlugField(blank=True, help_text='Subdomain prefix for this vendor (e.g., carbonilab).', max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Set to False if subscription lapses or vendor is disabled.')),
                ('plan_type', models.CharField(default='BASIC', help_text='Plan type for RBAC and feature gating.', max_length=50)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='LIS-specific settings (logo, timezone, features).')),
                ('billing_metadata', models.JSONField(blank=True, default=dict, help_text='External IDs: Stripe Customer ID, Subscription ID, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, help_text='The full domain/subdomain used by this vendor.', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'is_primary')},
            },
        ),
    ]
