# Generated by Django 5.2.7 on 2025-11-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='plan_type',
            field=models.CharField(choices=[('1', 'BASIC'), ('2', 'STANDARD'), ('2', 'PREMIUM'), ('3', 'PLATINUM')], default='BASIC', help_text='Plan type for this vendor.', max_length=50),
        ),
    ]
