# Generated by Django 5.2.7 on 2025-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='activation_email_sent',
            field=models.BooleanField(default=False, help_text='Whether activation email has been sent to tenant admin'),
        ),
    ]
