# Generated by Django 5.2.7 on 2025-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="tenant_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
