# Generated by Django 5.2.7 on 2025-11-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_vendor_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='configuration',
        ),
    ]
