# Generated by Django 5.2.7 on 2025-12-19 17:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_vendor_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendordomain',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='activation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='internal_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='plan_type',
            field=models.CharField(choices=[('1', 'BASIC'), ('2', 'STANDARD'), ('2', 'PREMIUM'), ('3', 'PLATINUM')], default='BASIC', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='subdomain_prefix',
            field=models.SlugField(blank=True, help_text='Subdomain prefix for this vendor (letters, numbers, hyphens only)', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='vendordomain',
            name='domain_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
