# Generated by Django 5.2.7 on 2026-02-19 10:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("REAGENT", "Reagent"),
                            ("CONSUMABLE", "Consumable"),
                            ("CONTROL", "Quality Control Material"),
                            ("CALIBRATOR", "Calibrator"),
                            ("EQUIPMENT", "Equipment Parts"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_categories",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory Categories",
                "unique_together": {("vendor", "name")},
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        help_text="Internal item code (e.g., RGT-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Reagent/Item name", max_length=200),
                ),
                ("manufacturer", models.CharField(max_length=200)),
                (
                    "catalog_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer's catalog/part number",
                        max_length=100,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        default="pcs",
                        help_text="ml, L, tests, pcs, boxes",
                        max_length=50,
                    ),
                ),
                (
                    "pack_size",
                    models.IntegerField(
                        default=1,
                        help_text="Number of units per pack (e.g., 100 tests/kit)",
                    ),
                ),
                (
                    "storage_condition",
                    models.CharField(
                        choices=[
                            ("RT", "Room Temperature (15-25°C)"),
                            ("FRIDGE", "Refrigerated (2-8°C)"),
                            ("FREEZER", "Frozen (-20°C)"),
                            ("DEEP_FREEZE", "Deep Freeze (-80°C)"),
                            ("SPECIAL", "Special Storage"),
                        ],
                        default="RT",
                        max_length=20,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True, help_text="Shelf/Cabinet location", max_length=100
                    ),
                ),
                (
                    "reorder_level",
                    models.IntegerField(
                        help_text="Alert when stock reaches this level",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_stock",
                    models.IntegerField(
                        help_text="Minimum stock to maintain",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_stock",
                    models.IntegerField(
                        help_text="Maximum stock capacity",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="Cost per unit", max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_barcode", models.BooleanField(default=False)),
                ("requires_lot_tracking", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "tests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which tests use this reagent",
                        related_name="required_reagents",
                        to="labs.vendortest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=50, unique=True)),
                ("supplier", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("ORDERED", "Ordered"),
                            ("PARTIAL", "Partially Received"),
                            ("COMPLETE", "Complete"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("actual_delivery", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "quantity_received",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        help_text="Manufacturer's lot/batch number", max_length=100
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Internal barcode for scanning",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "quantity_received",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "quantity_remaining",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "opened_date",
                    models.DateField(
                        blank=True,
                        help_text="Date vial/bottle was first opened",
                        null=True,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Freezer A, Shelf 2, Box 3",
                        max_length=100,
                    ),
                ),
                ("supplier", models.CharField(max_length=200)),
                ("purchase_order", models.CharField(blank=True, max_length=100)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("QUARANTINE", "Quarantine"),
                            ("EXPIRED", "Expired"),
                            ("DEPLETED", "Depleted"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_lots",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "-received_date"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_adjusted",
                    models.IntegerField(help_text="Positive = Add, Negative = Remove"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGE", "Damaged"),
                            ("EXPIRED", "Expired Disposal"),
                            ("CORRECTION", "Inventory Correction"),
                            ("TRANSFER", "Transfer to Another Lab"),
                            ("RETURN", "Return to Supplier"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField()),
                ("adjusted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adjusted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="inventory.stocklot",
                    ),
                ),
            ],
            options={
                "ordering": ["-adjusted_at"],
            },
        ),
        migrations.CreateModel(
            name="ReagentUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("TEST", "Patient Test"),
                            ("QC", "Quality Control"),
                            ("CALIBRATION", "Calibration"),
                            ("MAINTENANCE", "Maintenance"),
                            ("WASTE", "Waste/Spillage"),
                        ],
                        default="TEST",
                        max_length=20,
                    ),
                ),
                ("used_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "calibration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibration_usage",
                        to="labs.equipment",
                    ),
                ),
                (
                    "qc_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_usage",
                        to="labs.qcresult",
                    ),
                ),
                (
                    "test_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_usage",
                        to="labs.testassignment",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="inventory.stocklot",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Freezer A', 'Fridge 2'", max_length=100
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("FREEZER_-80", "Ultra-Low Freezer (-80°C)"),
                            ("FREEZER_-20", "Freezer (-20°C)"),
                            ("FRIDGE", "Refrigerator (2-8°C)"),
                            ("ROOM_TEMP", "Room Temperature Storage"),
                            ("INCUBATOR", "Incubator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location in lab", max_length=200
                    ),
                ),
                ("total_shelves", models.IntegerField(default=1)),
                (
                    "total_racks",
                    models.IntegerField(default=1, help_text="Racks per shelf"),
                ),
                (
                    "total_boxes",
                    models.IntegerField(default=1, help_text="Boxes per rack"),
                ),
                (
                    "target_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target temperature in °C",
                        max_digits=5,
                    ),
                ),
                (
                    "current_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_temp_check", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_units",
                        to="tenants.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelf_number", models.IntegerField()),
                ("rack_number", models.IntegerField(default=1)),
                ("box_number", models.IntegerField(default=1)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Position within box (e.g., A1, B3)",
                        max_length=10,
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        help_text="Auto-generated: FRZ-A-S2-R1-B3-A1",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "storage_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="inventory.storageunit",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "storage_unit",
                    "shelf_number",
                    "rack_number",
                    "box_number",
                    "position",
                ],
            },
        ),
        migrations.CreateModel(
            name="StoredSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=100, unique=True)),
                (
                    "sample_type",
                    models.CharField(
                        help_text="Serum, Plasma, Whole Blood", max_length=100
                    ),
                ),
                (
                    "stored_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "retention_days",
                    models.IntegerField(default=30, help_text="Days to keep sample"),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STORED", "Stored"),
                            ("RETRIEVED", "Retrieved"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="STORED",
                        max_length=20,
                    ),
                ),
                ("retrieved_date", models.DateTimeField(blank=True, null=True)),
                ("retrieval_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "retrieved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieved_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_samples",
                        to="inventory.storagelocation",
                    ),
                ),
                (
                    "stored_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_samples",
                        to="labs.testrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-stored_date"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["vendor", "is_active"], name="inventory_i_vendor__9d349d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(
                fields=["expiry_date", "is_available"],
                name="inventory_s_expiry__c89f02_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stocklot",
            unique_together={("item", "lot_number")},
        ),
        migrations.AddIndex(
            model_name="reagentusage",
            index=models.Index(
                fields=["stock_lot", "used_at"], name="inventory_r_stock_l_3e9332_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storageunit",
            unique_together={("vendor", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="storagelocation",
            unique_together={
                (
                    "storage_unit",
                    "shelf_number",
                    "rack_number",
                    "box_number",
                    "position",
                )
            },
        ),
        migrations.AddIndex(
            model_name="storedsample",
            index=models.Index(
                fields=["storage_location", "status"],
                name="inventory_s_storage_241adf_idx",
            ),
        ),
    ]
