# Generated by Django 5.2.7 on 2025-12-09 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("labs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Freezer A', 'Fridge 2'", max_length=100
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("FREEZER_-80", "Ultra-Low Freezer (-80°C)"),
                            ("FREEZER_-20", "Freezer (-20°C)"),
                            ("FRIDGE", "Refrigerator (2-8°C)"),
                            ("ROOM_TEMP", "Room Temperature Storage"),
                            ("INCUBATOR", "Incubator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Physical location in lab", max_length=200
                    ),
                ),
                ("total_shelves", models.IntegerField(default=1)),
                (
                    "total_racks",
                    models.IntegerField(default=1, help_text="Racks per shelf"),
                ),
                (
                    "total_boxes",
                    models.IntegerField(default=1, help_text="Boxes per rack"),
                ),
                (
                    "target_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target temperature in °C",
                        max_digits=5,
                    ),
                ),
                (
                    "current_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_temp_check", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_units",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "name")},
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelf_number", models.IntegerField()),
                ("rack_number", models.IntegerField(default=1)),
                ("box_number", models.IntegerField(default=1)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Position within box (e.g., A1, B3)",
                        max_length=10,
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        help_text="Auto-generated: FRZ-A-S2-R1-B3-A1",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "storage_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="inventory.storageunit",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "storage_unit",
                    "shelf_number",
                    "rack_number",
                    "box_number",
                    "position",
                ],
                "unique_together": {
                    (
                        "storage_unit",
                        "shelf_number",
                        "rack_number",
                        "box_number",
                        "position",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="StoredSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_id", models.CharField(max_length=100, unique=True)),
                (
                    "sample_type",
                    models.CharField(
                        help_text="Serum, Plasma, Whole Blood", max_length=100
                    ),
                ),
                (
                    "stored_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "retention_days",
                    models.IntegerField(default=30, help_text="Days to keep sample"),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STORED", "Stored"),
                            ("RETRIEVED", "Retrieved"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="STORED",
                        max_length=20,
                    ),
                ),
                ("retrieved_date", models.DateTimeField(blank=True, null=True)),
                ("retrieval_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "retrieved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieved_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_samples",
                        to="inventory.storagelocation",
                    ),
                ),
                (
                    "stored_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_samples",
                        to="labs.testrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-stored_date"],
                "indexes": [
                    models.Index(
                        fields=["storage_location", "status"],
                        name="inventory_s_storage_241adf_idx",
                    )
                ],
            },
        ),
    ]
