# Generated by Django 5.2.7 on 2026-02-19 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(default="SOP", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("requires_training", models.BooleanField(default=False)),
                ("retention_period_days", models.IntegerField(default=2555)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_doc_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_categories",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Document Categories",
                "ordering": ["code", "name"],
                "unique_together": {("vendor", "code")},
            },
        ),
        migrations.CreateModel(
            name="ControlledDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("purpose", models.TextField(blank=True)),
                ("scope", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("effective", "Effective"),
                            ("obsolete", "Obsolete"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("review_frequency_days", models.IntegerField(default=365)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx", "xlsx", "txt"]
                            )
                        ],
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("requires_electronic_signature", models.BooleanField(default=True)),
                ("requires_training", models.BooleanField(default=False)),
                ("is_controlled", models.BooleanField(default=True)),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_documents",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="doc_control.documentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("portal", "Portal Access"),
                            ("print", "Printed Copy"),
                        ],
                        default="portal",
                        max_length=20,
                    ),
                ),
                ("requires_acknowledgment", models.BooleanField(default=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledgment_signature",
                    models.CharField(blank=True, max_length=255),
                ),
                ("distributed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distributed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distributed_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_distributions",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-distributed_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("related", "Related Document"),
                            ("supersedes", "Supersedes"),
                            ("supplement", "Supplementary Document"),
                            ("procedure", "Referenced Procedure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referenced_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenced_by",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references_made",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_references",
                        to="tenants.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Review"),
                            ("periodic", "Periodic Review"),
                            ("change", "Change Control Review"),
                            ("audit", "Audit Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("comments", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("review_completed_at", models.DateTimeField(blank=True, null=True)),
                ("approval_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_reviews",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("reviewer", "Reviewer"),
                            ("approver", "Approver"),
                            ("quality", "Quality Assurance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("signature", models.CharField(max_length=255)),
                ("reason_for_signature", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_approvals",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to="doc_control.documentreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Training"),
                            ("refresher", "Refresher Training"),
                            ("update", "Update Training"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="required",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "assessment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("assessment_passed", models.BooleanField(default=False)),
                (
                    "training_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_trainings",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=20)),
                (
                    "change_description",
                    models.TextField(
                        help_text="Summary of changes made in this version"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("major", "Major Revision"),
                            ("minor", "Minor Revision"),
                            ("editorial", "Editorial Change"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/versions/%Y/%m/")),
                ("file_size", models.IntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("obsolete_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versioned_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Document Created"),
                            ("updated", "Document Updated"),
                            ("viewed", "Document Viewed"),
                            ("downloaded", "Document Downloaded"),
                            ("printed", "Document Printed"),
                            ("approved", "Document Approved"),
                            ("rejected", "Document Rejected"),
                            ("obsoleted", "Document Obsoleted"),
                            ("retired", "Document Retired"),
                            ("distributed", "Document Distributed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_full_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="doc_control.controlleddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_audit_logs",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "document"],
                        name="doc_control_vendor__df4610_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="doc_control_timesta_d2db31_idx"
                    ),
                    models.Index(
                        fields=["action"], name="doc_control_action_5ff63e_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="controlleddocument",
            index=models.Index(
                fields=["vendor", "status"], name="doc_control_vendor__a0bc7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlleddocument",
            index=models.Index(
                fields=["document_number"], name="doc_control_documen_14070c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlleddocument",
            index=models.Index(
                fields=["next_review_date"], name="doc_control_next_re_758a7a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="controlleddocument",
            unique_together={("vendor", "document_number", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="documentdistribution",
            unique_together={("document", "distributed_to")},
        ),
        migrations.AlterUniqueTogether(
            name="documentreference",
            unique_together={("source_document", "referenced_document")},
        ),
        migrations.AddIndex(
            model_name="documentreview",
            index=models.Index(
                fields=["vendor", "status"], name="doc_control_vendor__209f5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentreview",
            index=models.Index(
                fields=["due_date"], name="doc_control_due_dat_104fe3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentapproval",
            index=models.Index(
                fields=["vendor", "document"], name="doc_control_vendor__2ced5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documenttraining",
            unique_together={("document", "trainee", "training_type")},
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version_number")},
        ),
    ]
