# Generated by Django 5.2.7 on 2026-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Critical/Error"),
                ],
                default="info",
                max_length=10,
            ),
        ),
    ]
