# Generated by Django 5.2.7 on 2026-01-09 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_level"),
        ("notification", "0003_seed_system_templates"),
    ]

    operations = []
