# Generated by Django 5.2.7 on 2026-02-07 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preferred_notification",
                    models.CharField(
                        choices=[
                            ("email", "Email Only"),
                            ("sms", "SMS Only"),
                            ("both", "Email & SMS"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "consent_to_digital_results",
                    models.BooleanField(
                        default=False,
                        help_text="Patient consents to viewing results online",
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                (
                    "profile_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Has patient filled all required profile fields?",
                    ),
                ),
                ("language_preference", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_portal_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        help_text="Link to lab operations patient record",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_account",
                        to="labs.patient",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Link to authenticated user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient User Profile",
                "verbose_name_plural": "Patient User Profiles",
                "indexes": [
                    models.Index(
                        fields=["user"], name="patient_pat_user_id_fc6eee_idx"
                    ),
                    models.Index(
                        fields=["patient"], name="patient_pat_patient_f82c94_idx"
                    ),
                ],
                "unique_together": {("user", "patient")},
            },
        ),
    ]
