# Generated by Django 5.2.7 on 2025-12-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0003_testrequest_approved_at_testrequest_approved_by_and_more"),
        ("patient", "0001_initial"),
        ("tenants", "0004_alter_vendordomain_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Appointment date")),
                ("start_time", models.TimeField(help_text="Slot start time")),
                ("end_time", models.TimeField(help_text="Slot end time")),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        default=1, help_text="How many patients can book this slot"
                    ),
                ),
                (
                    "current_bookings",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of bookings"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this slot available for booking?"
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("sample_collection", "Sample Collection"),
                            ("consultation", "Consultation"),
                            ("result_discussion", "Result Discussion"),
                            ("general", "General Visit"),
                        ],
                        default="sample_collection",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_slots",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_id",
                    models.CharField(
                        help_text="Auto-generated appointment ID",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("visitor_first_name", models.CharField(blank=True, max_length=100)),
                ("visitor_last_name", models.CharField(blank=True, max_length=100)),
                ("visitor_email", models.EmailField(blank=True, max_length=254)),
                ("visitor_phone", models.CharField(blank=True, max_length=15)),
                ("visitor_date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "visitor_gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("sample_collection", "Sample Collection"),
                            ("consultation", "Consultation"),
                            ("result_discussion", "Result Discussion"),
                            ("test_request", "New Test Request"),
                        ],
                        default="sample_collection",
                        max_length=20,
                    ),
                ),
                (
                    "reason_for_visit",
                    models.TextField(
                        blank=True, help_text="Patient's notes about the visit"
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Any special needs (wheelchair access, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("confirmation_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booked_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the booking (if authenticated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked patient record (created if doesn't exist)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="labs.patient",
                    ),
                ),
                (
                    "test_request",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to test request if appointment is for sample collection",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment",
                        to="labs.testrequest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patient.appointmentslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSlotTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Morning Sample Collection')",
                        max_length=100,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Slot start time")),
                ("end_time", models.TimeField(help_text="Slot end time")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Slot duration in minutes"
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.CharField(
                        choices=[
                            ("weekdays", "Weekdays (Mon-Fri)"),
                            ("weekends", "Weekends (Sat-Sun)"),
                            ("daily", "Daily"),
                            ("specific_days", "Specific Days of Week"),
                        ],
                        default="weekdays",
                        max_length=20,
                    ),
                ),
                ("monday", models.BooleanField(default=False)),
                ("tuesday", models.BooleanField(default=False)),
                ("wednesday", models.BooleanField(default=False)),
                ("thursday", models.BooleanField(default=False)),
                ("friday", models.BooleanField(default=False)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        default=1, help_text="Max bookings per slot"
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("sample_collection", "Sample Collection"),
                            ("consultation", "Consultation"),
                            ("result_discussion", "Result Discussion"),
                            ("general", "General Visit"),
                        ],
                        default="sample_collection",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_slot_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_templates",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["vendor", "date", "is_active"],
                name="patient_app_vendor__5efad1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together={("vendor", "date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["vendor", "status"], name="patient_app_vendor__22664c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="patient_app_patient_cf6ec2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_id"], name="patient_app_appoint_4fae20_idx"
            ),
        ),
    ]
