# Generated by Django 5.2.7 on 2026-01-05 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0004_remove_testresult_labs_testre_assignm_fe411e_idx_and_more"),
        (
            "patient",
            "0002_appointmentslot_appointment_appointmentslottemplate_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointmentslot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="appointmentslot",
            name="vendor",
        ),
        migrations.RemoveField(
            model_name="appointmentslottemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="appointmentslottemplate",
            name="vendor",
        ),
        migrations.AlterUniqueTogether(
            name="patientuser",
            unique_together={("user", "patient")},
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="AppointmentSlot",
        ),
        migrations.DeleteModel(
            name="AppointmentSlotTemplate",
        ),
    ]
