# Generated by Django 5.2.7 on 2025-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_coursecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price of the course in USD. Set to 0.00 for free courses.', max_digits=8),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, editable=False, help_text='Automatically set to True if base_price is 0.00'),
        ),
    ]
