# Generated by Django 5.2.7 on 2025-12-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_course_base_price_course_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='learn.course'),
        ),
    ]
