# Generated by Django 5.2.7 on 2025-10-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=64)),
                ("patient_name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=32)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("raw_payload", models.JSONField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.vendor"
                    ),
                ),
            ],
        ),
    ]
