# Generated by Django 5.2.7 on 2026-02-07 16:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Department",
                "ordering": ["name"],
                "unique_together": {("vendor", "name")},
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("model", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="Windows LIMS API endpoint for this instrument",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="Authentication key", max_length=255
                    ),
                ),
                (
                    "supports_auto_fetch",
                    models.BooleanField(
                        default=False, help_text="Can automatically fetch results"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Under Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_calibrated", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="labs.department",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_set",
                        to="tenants.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        help_text="Auto-generated 6-digit patient ID.", max_length=20
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "is_shadow",
                    models.BooleanField(
                        default=False,
                        help_text="True if created via a walk-in appointment without a full account.",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
                "unique_together": {("vendor", "patient_id")},
            },
        ),
        migrations.CreateModel(
            name="QCLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        help_text="Manufacturer's lot/batch number", max_length=100
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L1", "Level 1 - Low"),
                            ("L2", "Level 2 - Normal"),
                            ("L3", "Level 3 - High"),
                        ],
                        default="L2",
                        max_length=2,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="QC material manufacturer", max_length=200
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Expected/target value for this QC",
                        max_digits=10,
                    ),
                ),
                (
                    "sd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Standard deviation (optional if using explicit limits)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "explicit_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "explicit_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        choices=[
                            ("mg/dL", "mg/dL"),
                            ("mmol/L", "mmol/L"),
                            ("g/L", "g/L"),
                            ("g/dL", "g/dL"),
                            ("ng/mL", "ng/mL"),
                            ("µg/L", "µg/L"),
                            ("U/L", "U/L"),
                            ("IU/L", "IU/L"),
                            ("pg/mL", "pg/mL"),
                            ("mEq/L", "mEq/L"),
                            ("%", "Percent (%)"),
                        ],
                        default="mg/dL",
                        max_length=20,
                    ),
                ),
                (
                    "mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Mean value (same as target initially)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "limit_1sd_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "limit_1sd_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "limit_2sd_low",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "limit_2sd_high",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "limit_3sd_low",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "limit_3sd_high",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, help_text="Date QC lot was received", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date of QC material",
                        null=True,
                    ),
                ),
                (
                    "opened_date",
                    models.DateField(
                        blank=True, help_text="Date vial was opened", null=True
                    ),
                ),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Currently in use"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_lots",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Lot",
                "verbose_name_plural": "QC Lots",
                "ordering": ["-received_date", "test__name", "level"],
            },
        ),
        migrations.CreateModel(
            name="QCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_value", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "z_score",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "run_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("run_time", models.TimeField(default=django.utils.timezone.now)),
                ("run_number", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass - In Control"),
                            ("WARNING", "Warning - Near Limit"),
                            ("FAIL", "Fail - Out of Control"),
                        ],
                        default="PASS",
                        max_length=10,
                    ),
                ),
                ("rule_violations", models.JSONField(blank=True, default=list)),
                ("comments", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_results",
                        to="labs.equipment",
                    ),
                ),
                (
                    "qc_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="labs.qclot",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_results",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-run_date", "-run_time"],
            },
        ),
        migrations.CreateModel(
            name="QCAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("REPEAT", "Repeat QC"),
                            ("CALIBRATE", "Recalibrate Instrument"),
                            ("MAINTENANCE", "Instrument Maintenance"),
                            ("REAGENT", "Replace Reagent"),
                            ("NEW_LOT", "Open New QC Lot"),
                            ("SERVICE", "Call Service Engineer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of action taken"),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="labs.qcresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        help_text="Globally unique barcode/sample ID (auto-generated).",
                        max_length=64,
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        help_text="Specimen type e.g., Blood, Urine, Serum, Swab, etc.",
                        max_length=100,
                    ),
                ),
                ("specimen_description", models.TextField(blank=True, null=True)),
                (
                    "collected_by",
                    models.CharField(
                        blank=True,
                        help_text="Phlebotomist or technician name/ID.",
                        max_length=150,
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Venipuncture, Capillary, Finger prick.",
                        max_length=100,
                    ),
                ),
                (
                    "collection_site",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Left arm, finger prick.",
                        max_length=100,
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., EDTA tube, Serum separator, Plain bottle.",
                        max_length=100,
                    ),
                ),
                (
                    "volume_collected_ml",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volume in mL.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Accessioned"),
                            ("RJ", "Rejected"),
                            ("AP", "Accepted"),
                            ("ST", "Stored"),
                            ("CO", "Consumed"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Storage location or rack ID.",
                        max_length=200,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when verification occurred.",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if applicable.",
                        null=True,
                    ),
                ),
                (
                    "fasting_status",
                    models.CharField(
                        choices=[
                            ("fasting", "Fasting (8-12 hours)"),
                            ("non_fasting", "Non-Fasting"),
                            ("not_required", "Not Required"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Patient's fasting state at time of collection.",
                        max_length=20,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="labs.patient",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who verified this sample before analysis.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample / Specimen",
                "verbose_name_plural": "Samples / Specimens",
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=20)),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Rejected"),
                            ("F", "Freed"),
                            ("Q", "Queued"),
                            ("I", "In Progress"),
                            ("A", "Analysis Complete"),
                            ("V", "Result Verified"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When test was sent to instrument",
                        null=True,
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True, help_text="When result was received", null=True
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When result was verified", null=True
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, help_text="When result was released", null=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from Windows LIMS/instrument system",
                        max_length=100,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of failed attempts to send to instrument",
                    ),
                ),
                (
                    "last_sync_attempt",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time we tried to sync with instrument",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lab technician assigned to this test",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_work",
                        to="labs.department",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        help_text="The equipment used or scheduled to run this test.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="labs.equipment",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        help_text="The sample specimen required to run this test.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="labs.sample",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("send", "Sent to Instrument"),
                            ("receive", "Received from Instrument"),
                            ("error", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField(help_text="Request/response payload")),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="labs.equipment",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_logs",
                        to="labs.testassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Why was this order rejected?"
                    ),
                ),
                ("request_id", models.CharField(max_length=64)),
                ("clinical_history", models.TextField(blank=True)),
                ("clinical_indication", models.TextField(blank=True)),
                ("urgency_reason", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("urgent", "URGENT"), ("routine", "ROUTINE")],
                        default="routine",
                        max_length=45,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("W", "Awaiting Approval"),
                            ("A", "Approved"),
                            ("R", "Received"),
                            ("N", "Analysis"),
                            ("C", "Complete"),
                            ("V", "Verified"),
                            ("X", "Rejected"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("has_informed_consent", models.BooleanField(default=False)),
                ("collection_notes", models.TextField(blank=True)),
                (
                    "external_referral",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "barcode_image",
                    models.ImageField(blank=True, null=True, upload_to="barcodes/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("clinician_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clinician_acknowledged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff/clinician who approved patient self-order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordering_clinician",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clinician responsible for this order",
                        limit_choices_to={"role": "clinician"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="labs.patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this order (clinician or patient)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Request",
                "verbose_name_plural": "Test Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="testassignment",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="labs.testrequest",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="test_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="labs.testrequest",
            ),
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("verified", "Verified"),
                            ("released", "Released"),
                            ("amended", "Amended"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("result_value", models.TextField()),
                ("units", models.CharField(blank=True, max_length=50)),
                ("reference_range", models.CharField(blank=True, max_length=80)),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("N", "Normal"),
                            ("H", "High"),
                            ("L", "Low"),
                            ("A", "Abnormal"),
                            ("C", "Critical"),
                            ("M", "Unmeasurable (Outside AMR)"),
                            ("R", "Out of Reportable Range"),
                            ("*", "Corrected"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("interpretation", models.TextField(blank=True)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("instrument", "Instrument Generated"),
                            ("imported", "Imported"),
                            ("calculated", "Calculated"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("instrument_name", models.CharField(blank=True, max_length=150)),
                ("instrument_run_id", models.CharField(blank=True, max_length=100)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("is_amended", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("previous_value", models.TextField(blank=True)),
                ("amendment_reason", models.TextField(blank=True)),
                ("qc_passed", models.BooleanField(default=True)),
                ("qc_comment", models.TextField(blank=True)),
                ("delta_flag", models.BooleanField(default=False)),
                (
                    "delta_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="labs.testassignment",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Result",
                "verbose_name_plural": "Test Results",
                "ordering": ["-entered_at"],
                "permissions": [
                    ("can_verify_results", "Can verify test results"),
                    ("can_release_results", "Can release test results"),
                    ("can_amend_results", "Can amend released results"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResultAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("reason", models.TextField()),
                ("amended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_history",
                        to="labs.testresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Amendment",
                "ordering": ["-amended_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "available_for_online_booking",
                    models.BooleanField(
                        default=False,
                        help_text="Can patients request this test online without clinician referral?",
                    ),
                ),
                (
                    "requires_physician_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Patient orders require physician review before processing (used for complex/high-risk tests)",
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Serum, Plasma, Urine",
                        max_length=100,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="Analytical method / platform",
                        max_length=120,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        help_text="Instrument/platform name (optional)",
                        max_length=120,
                    ),
                ),
                (
                    "default_units",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[("QNT", "Quantitative"), ("QLT", "Qualitative")],
                        default="QNT",
                        max_length=3,
                    ),
                ),
                (
                    "amr_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Analytical Measuring Range (lower)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "amr_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Analytical Measuring Range (upper)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reportable_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Reportable (clinical) low",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reportable_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Reportable (clinical) high",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_reference_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "max_reference_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "panic_low_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Critical low (panic) threshold",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "panic_high_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Critical high (panic) threshold",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "preparation_required",
                    models.BooleanField(
                        default=False,
                        help_text="Does this test require special preparation? (fasting, medication hold, etc.)",
                    ),
                ),
                (
                    "preparation_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Patient-facing instructions (e.g., 'Fast for 8-12 hours', 'Avoid alcohol 48hrs before')",
                    ),
                ),
                (
                    "collection_instructions",
                    models.TextField(
                        blank=True,
                        help_text="How the sample should be collected (e.g., 'First morning urine', 'Avoid recent exercise')",
                    ),
                ),
                (
                    "patient_friendly_description",
                    models.TextField(
                        blank=True,
                        help_text="Layman's explanation of what this test measures and why it's ordered",
                    ),
                ),
                (
                    "typical_reasons",
                    models.TextField(
                        blank=True,
                        help_text="Common clinical indications for this test (for patient education)",
                    ),
                ),
                ("turnaround_override", models.DurationField(blank=True, null=True)),
                ("general_comment_template", models.TextField(blank=True)),
                (
                    "enabled_for_autoverify",
                    models.BooleanField(
                        default=False,
                        help_text="Allow autoverification under configured rules (QC pass, instrument source, delta check, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="labs.department",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Test",
                "verbose_name_plural": "Lab Tests",
            },
        ),
        migrations.AddField(
            model_name="testrequest",
            name="requested_tests",
            field=models.ManyToManyField(
                related_name="test_requests", to="labs.vendortest"
            ),
        ),
        migrations.AddField(
            model_name="testassignment",
            name="lab_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="labs.vendortest",
            ),
        ),
        migrations.CreateModel(
            name="QualitativeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=120)),
                (
                    "normalized",
                    models.CharField(
                        blank=True,
                        help_text="Normalized lowercase value for fast comparisons (auto-filled on save).",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "is_normal",
                    models.BooleanField(
                        default=False,
                        help_text="Marks this option as clinically normal",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Sort order for display"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qlt_options",
                        to="labs.vendortest",
                    ),
                ),
            ],
            options={
                "ordering": ("test", "order", "value"),
            },
        ),
        migrations.CreateModel(
            name="QCTestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Test approved for patient testing today",
                    ),
                ),
                (
                    "all_levels_passed",
                    models.BooleanField(
                        default=False, help_text="All QC levels passed"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_results",
                    models.ManyToManyField(
                        related_name="test_approvals", to="labs.qcresult"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_approvals",
                        to="tenants.vendor",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_qc_status",
                        to="labs.vendortest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily QC Approval",
                "verbose_name_plural": "Daily QC Approvals",
                "ordering": ["-date", "test__name"],
            },
        ),
        migrations.AddField(
            model_name="qclot",
            name="test",
            field=models.ForeignKey(
                help_text="Which test this QC lot is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qc_lots",
                to="labs.vendortest",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "-created_at"],
                        name="labs_auditl_vendor__a5cde1_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(
                fields=["vendor", "run_date"], name="labs_qcresu_vendor__55feb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(
                fields=["qc_lot", "run_date"], name="labs_qcresu_qc_lot__ff3227_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(
                fields=["status", "is_approved"], name="labs_qcresu_status_b9e2f1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sequencecounter",
            unique_together={("vendor", "prefix")},
        ),
        migrations.AddIndex(
            model_name="instrumentlog",
            index=models.Index(
                fields=["assignment", "log_type"], name="labs_instru_assignm_8647e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("vendor", "sample_id"), name="unique_sample_per_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["status"], name="labs_testre_status_c62e01_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["entered_at"], name="labs_testre_entered_3d7694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["verified_at"], name="labs_testre_verifie_99a401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["released_at"], name="labs_testre_release_528c38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["flag"], name="labs_testre_flag_a92081_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["flag", "data_source"], name="labs_testre_flag_d264bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendortest",
            index=models.Index(
                fields=["vendor", "code"], name="labs_vendor_vendor__ba0afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendortest",
            index=models.Index(
                fields=["result_type"], name="labs_vendor_result__bbf590_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendortest",
            index=models.Index(
                fields=["amr_low", "amr_high"], name="labs_vendor_amr_low_1b57b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendortest",
            index=models.Index(
                fields=["available_for_online_booking"],
                name="labs_vendor_availab_e7c7ad_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vendortest",
            unique_together={("vendor", "code")},
        ),
        migrations.AddIndex(
            model_name="testrequest",
            index=models.Index(
                fields=["ordering_clinician", "status"],
                name="labs_testre_orderin_a417df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testrequest",
            index=models.Index(
                fields=["patient", "created_at"], name="labs_testre_patient_3cf08f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testrequest",
            index=models.Index(
                fields=["status", "created_at"], name="labs_testre_status_13d82c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="testrequest",
            constraint=models.UniqueConstraint(
                fields=("vendor", "request_id"), name="unique_request_id_per_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="testassignment",
            index=models.Index(
                fields=["status", "instrument"], name="labs_testas_status_7f7b3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testassignment",
            index=models.Index(
                fields=["external_id"], name="labs_testas_externa_a50fcf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testassignment",
            unique_together={("request", "lab_test")},
        ),
        migrations.AlterUniqueTogether(
            name="qualitativeoption",
            unique_together={("test", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="qctestapproval",
            unique_together={("vendor", "test", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="qclot",
            unique_together={("vendor", "test", "lot_number", "level")},
        ),
    ]
