# Generated by Django 5.2.7 on 2025-11-14 05:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Department',
                'ordering': ['name'],
                'unique_together': {('vendor', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField(blank=True, help_text='Windows LIMS API endpoint for this instrument')),
                ('api_key', models.CharField(blank=True, help_text='Authentication key', max_length=255)),
                ('supports_auto_fetch', models.BooleanField(default=False, help_text='Can automatically fetch results')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='labs.department')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='tenants.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Auto-generated 6-digit patient ID.', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='tenants.vendor')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('vendor', 'patient_id')},
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='Unique Request/Order ID (auto-generated).', max_length=64, unique=True)),
                ('clinical_history', models.TextField(blank=True, help_text='Relevant clinical notes or history.')),
                ('priority', models.CharField(default='routine', help_text='e.g., routine, urgent, stat.', max_length=32)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Received'), ('A', 'Analysis'), ('C', 'Complete'), ('V', 'Verified')], default='P', max_length=1)),
                ('has_informed_consent', models.BooleanField(default=False, help_text='Indicates that informed consent was obtained.')),
                ('collection_notes', models.TextField(blank=True, help_text='Additional notes on phlebotomy or collection (time deviations, complications, etc.).')),
                ('external_referral', models.CharField(blank=True, help_text='Referring doctor or institution, if any.', max_length=255, null=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='labs.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Test Request',
                'verbose_name_plural': 'Test Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(help_text='Globally unique barcode/sample ID (auto-generated).', max_length=64, unique=True)),
                ('specimen_type', models.CharField(help_text='Specimen type e.g., Blood, Urine, Serum, Swab, etc.', max_length=100)),
                ('specimen_description', models.TextField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, help_text='Phlebotomist or technician name/ID.', max_length=150)),
                ('collection_method', models.CharField(blank=True, help_text='e.g., Venipuncture, Capillary, Finger prick.', max_length=100)),
                ('collection_site', models.CharField(blank=True, help_text='e.g., Left arm, finger prick.', max_length=100)),
                ('container_type', models.CharField(blank=True, help_text='e.g., EDTA tube, Serum separator, Plain bottle.', max_length=100)),
                ('volume_collected_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Volume in mL.', max_digits=5, null=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AC', 'Accessioned'), ('RJ', 'Rejected'), ('AP', 'Accepted'), ('ST', 'Stored'), ('CO', 'Consumed')], default='AC', max_length=2)),
                ('location', models.CharField(blank=True, help_text='Storage location or rack ID.', max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when verification occurred.', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable.', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='labs.patient')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='tenants.vendor')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff who verified this sample before analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_samples', to=settings.AUTH_USER_MODEL)),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='labs.testrequest')),
            ],
            options={
                'verbose_name': 'Sample / Specimen',
                'verbose_name_plural': 'Samples / Specimens',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('INS', 'Insurance'), ('PAT', 'Patient Self-Pay'), ('ACC', 'Client Account')], default='PAT', max_length=3)),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='tenants.vendor')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='labs.testrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VendorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('turnaround_override', models.DurationField(blank=True, help_text='Test Time of completion.', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('specimen_type', models.CharField(help_text='Blood, Urine, Tissue, etc.', max_length=100)),
                ('default_units', models.CharField(blank=True, max_length=50, null=True)),
                ('default_reference_text', models.CharField(blank=True, max_length=255, null=True)),
                ('result_type', models.CharField(choices=[('QNT', 'Quantitative'), ('QLT', 'Qualitative')], default='QNT', max_length=3)),
                ('min_reference_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Minimum reference value for a particular test', max_digits=6, null=True)),
                ('max_reference_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Maximum reference value for a particular test', max_digits=6, null=True)),
                ('general_comment_template', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_department', models.ForeignKey(help_text='The department in this lab responsible for running the test.', on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='labs.department')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='tenants.vendor')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'unique_together': {('vendor', 'code')},
            },
        ),
        migrations.AddField(
            model_name='testrequest',
            name='requested_tests',
            field=models.ManyToManyField(related_name='test_requests', to='labs.vendortest'),
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('Q', 'Queued'), ('I', 'In Progress'), ('A', 'Analysis Complete'), ('V', 'Result Verified')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queued_at', models.DateTimeField(blank=True, help_text='When test was sent to instrument', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='When result was received', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When result was verified', null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID from Windows LIMS/instrument system', max_length=100)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of failed attempts to send to instrument')),
                ('last_sync_attempt', models.DateTimeField(blank=True, help_text='Last time we tried to sync with instrument', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Lab technician assigned to this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work', to='labs.department')),
                ('instrument', models.ForeignKey(blank=True, help_text='The equipment used or scheduled to run this test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='labs.equipment')),
                ('sample', models.ForeignKey(help_text='The sample specimen required to run this test.', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='labs.sample')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenants.vendor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='labs.testrequest')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='labs.vendortest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='labs_auditl_vendor__a5cde1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('send', 'Sent to Instrument'), ('receive', 'Received from Instrument'), ('error', 'Error')], max_length=10)),
                ('payload', models.JSONField(help_text='Request/response payload')),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.equipment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_logs', to='labs.testassignment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment', 'log_type'], name='labs_instru_assignm_8647e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField(help_text='The measured value.')),
                ('units', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=80)),
                ('flag', models.CharField(choices=[('N', 'Normal'), ('H', 'High'), ('L', 'Low'), ('A', 'Abnormal'), ('C', 'Critical')], default='N', max_length=1)),
                ('remarks', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True, help_text='Clinical interpretation')),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('instrument', 'Instrument'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('previous_value', models.TextField(blank=True, help_text='Previous result value if edited')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='labs.testassignment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entered_at'], name='labs_testre_entered_3d7694_idx'), models.Index(fields=['verified_at'], name='labs_testre_verifie_99a401_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['status', 'instrument'], name='labs_testas_status_7f7b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['external_id'], name='labs_testas_externa_a50fcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testassignment',
            unique_together={('request', 'lab_test')},
        ),
    ]
