# Generated by Django 5.2.7 on 2025-12-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='clinical_indication',
            field=models.TextField(blank=True, help_text='Reason for ordering tests (ICD codes, symptoms, diagnosis)'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='clinician_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When did clinician acknowledge reviewing results?', null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='clinician_notified_at',
            field=models.DateTimeField(blank=True, help_text='When was the ordering clinician notified of results?', null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='ordering_clinician',
            field=models.ForeignKey(blank=True, help_text='Clinician responsible for this order', limit_choices_to={'role': 'clinician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='urgency_reason',
            field=models.TextField(blank=True, help_text='Justification for urgent/STAT orders'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who created this order (clinician or patient)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['ordering_clinician', 'status'], name='labs_testre_orderin_a417df_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['patient', 'created_at'], name='labs_testre_patient_3cf08f_idx'),
        ),
    ]
