# Generated by Django 5.2.7 on 2026-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testassignment",
            name="released_at",
            field=models.DateTimeField(
                blank=True, help_text="When result was released", null=True
            ),
        ),
        migrations.AlterField(
            model_name="testassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Rejected"),
                    ("F", "Freed"),
                    ("Q", "Queued"),
                    ("I", "In Progress"),
                    ("A", "Analysis Complete"),
                    ("V", "Result Verified"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
