# Generated by Django 5.2.7 on 2025-11-25 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginformation',
            name='request',
        ),
        migrations.RemoveField(
            model_name='billinginformation',
            name='vendor',
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-entered_at'], 'permissions': [('can_verify_results', 'Can verify test results'), ('can_release_results', 'Can release test results'), ('can_amend_results', 'Can amend released results')], 'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.RemoveIndex(
            model_name='testresult',
            name='labs_testre_release_83fd2d_idx',
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['assignment', 'entered_at'], name='labs_testre_assignm_fe411e_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['released', 'verified_at'], name='labs_testre_release_0974c6_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['flag', 'data_source'], name='labs_testre_flag_d264bb_idx'),
        ),
        migrations.DeleteModel(
            name='BillingInformation',
        ),
    ]
