# Generated by Django 5.2.7 on 2025-11-19 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrequest",
            name="priority",
            field=models.CharField(
                choices=[("urgent", "URGENT"), ("routine", "ROUTINE")],
                default="routine",
                help_text="e.g., routine, urgent, stat.",
                max_length=45,
            ),
        ),
        migrations.CreateModel(
            name="QCLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(
                        help_text="Manufacturer's lot/batch number", max_length=100
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L1", "Level 1 - Low"),
                            ("L2", "Level 2 - Normal"),
                            ("L3", "Level 3 - High"),
                        ],
                        default="L2",
                        max_length=2,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="QC material manufacturer", max_length=200
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Expected/target value for this QC",
                        max_digits=10,
                    ),
                ),
                (
                    "sd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Standard deviation (optional if using explicit limits)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "explicit_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "explicit_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "units",
                    models.CharField(help_text="mg/dL, mmol/L, etc.", max_length=50),
                ),
                (
                    "mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Mean value (same as target initially)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "limit_1sd_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "limit_1sd_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "limit_2sd_low",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "limit_2sd_high",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "limit_3sd_low",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "limit_3sd_high",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, help_text="Date QC lot was received", null=True
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date of QC material",
                        null=True,
                    ),
                ),
                (
                    "opened_date",
                    models.DateField(
                        blank=True, help_text="Date vial was opened", null=True
                    ),
                ),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Currently in use"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.ForeignKey(
                        help_text="Which test this QC lot is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_lots",
                        to="labs.vendortest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_lots",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Lot",
                "verbose_name_plural": "QC Lots",
                "ordering": ["-received_date", "test__name", "level"],
                "unique_together": {("vendor", "test", "lot_number", "level")},
            },
        ),
        migrations.CreateModel(
            name="QCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_value",
                    models.DecimalField(
                        decimal_places=3, help_text="Measured QC value", max_digits=10
                    ),
                ),
                (
                    "run_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date QC was run",
                    ),
                ),
                (
                    "run_time",
                    models.TimeField(
                        default=django.utils.timezone.now, help_text="Time QC was run"
                    ),
                ),
                (
                    "run_number",
                    models.IntegerField(
                        default=1,
                        help_text="Run number for the day (1st run, 2nd run, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass - In Control"),
                            ("WARNING", "Warning - Near Limit"),
                            ("FAIL", "Fail - Out of Control"),
                        ],
                        default="PASS",
                        max_length=10,
                    ),
                ),
                (
                    "z_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Number of SDs from mean",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "rule_violations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of violated Westgard rules",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Comments about this QC run"
                    ),
                ),
                (
                    "corrective_action",
                    models.TextField(blank=True, help_text="Action taken if QC failed"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Approved for patient testing"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_results",
                        to="labs.equipment",
                    ),
                ),
                (
                    "qc_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="labs.qclot",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_results",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Result",
                "verbose_name_plural": "QC Results",
                "ordering": ["-run_date", "-run_time"],
            },
        ),
        migrations.CreateModel(
            name="QCAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("REPEAT", "Repeat QC"),
                            ("CALIBRATE", "Recalibrate Instrument"),
                            ("MAINTENANCE", "Instrument Maintenance"),
                            ("REAGENT", "Replace Reagent"),
                            ("NEW_LOT", "Open New QC Lot"),
                            ("SERVICE", "Call Service Engineer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of action taken"),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="labs.qcresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QCTestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Test approved for patient testing today",
                    ),
                ),
                (
                    "all_levels_passed",
                    models.BooleanField(
                        default=False, help_text="All QC levels passed"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_results",
                    models.ManyToManyField(
                        related_name="test_approvals", to="labs.qcresult"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_qc_status",
                        to="labs.vendortest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_approvals",
                        to="tenants.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily QC Approval",
                "verbose_name_plural": "Daily QC Approvals",
                "ordering": ["-date", "test__name"],
            },
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(
                fields=["vendor", "run_date"], name="labs_qcresu_vendor__55feb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(
                fields=["qc_lot", "run_date"], name="labs_qcresu_qc_lot__ff3227_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcresult",
            index=models.Index(
                fields=["status", "is_approved"], name="labs_qcresu_status_b9e2f1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qctestapproval",
            unique_together={("vendor", "test", "date")},
        ),
    ]
