# Generated by Django 5.2.7 on 2025-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendortest",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
