# Generated by Django 5.2.7 on 2025-10-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendortest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="vendortest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="globaltest",
            name="default_turnaround",
            field=models.DurationField(
                blank=True,
                help_text="the expected time it takes to complete the test.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendortest",
            name="turnaround_override",
            field=models.DurationField(
                blank=True,
                help_text="the expected time it takes to complete the test.",
                null=True,
            ),
        ),
    ]
