# Generated by Django 5.2.7 on 2025-11-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_vendortest_slug"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["-collected_at"],
                "verbose_name": "Sample / Specimen",
                "verbose_name_plural": "Samples / Specimens",
            },
        ),
        migrations.AlterModelOptions(
            name="testrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Test Request",
                "verbose_name_plural": "Test Requests",
            },
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="contact_number",
            new_name="contact_phone",
        ),
        migrations.AddField(
            model_name="sample",
            name="collection_method",
            field=models.CharField(
                blank=True,
                help_text="e.g., Venipuncture, Capillary, Finger prick.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="collection_site",
            field=models.CharField(
                blank=True, help_text="e.g., Left arm, finger prick.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="container_type",
            field=models.CharField(
                blank=True,
                help_text="e.g., EDTA tube, Serum separator, Plain bottle.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="specimen_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="volume_collected_ml",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Volume collected in milliliters.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testrequest",
            name="collection_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes on phlebotomy or collection (time deviations, complications, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="testrequest",
            name="external_referral",
            field=models.CharField(
                blank=True,
                help_text="Referring doctor or institution, if any.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="testrequest",
            name="has_informed_consent",
            field=models.BooleanField(
                default=False, help_text="Indicates that informed consent was obtained."
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="collected_by",
            field=models.CharField(
                blank=True,
                help_text="Name or ID of the phlebotomist/technician.",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="location",
            field=models.CharField(
                blank=True, help_text="Storage location or rack ID.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="sample_id",
            field=models.CharField(
                help_text="Globally unique barcode/sample ID (auto-generated).",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="specimen_type",
            field=models.CharField(
                help_text="Specimen type e.g., Blood, Urine, Serum, Swab, etc.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Accessioned"),
                    ("R", "Rejected"),
                    ("C", "Consumed"),
                    ("S", "Stored"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="testrequest",
            name="clinical_history",
            field=models.TextField(
                blank=True, help_text="Relevant clinical notes or history."
            ),
        ),
        migrations.AlterField(
            model_name="testrequest",
            name="priority",
            field=models.CharField(
                default="routine",
                help_text="e.g., routine, urgent, stat.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="testrequest",
            name="request_id",
            field=models.CharField(
                help_text="Unique Request/Order ID (auto-generated).",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="BillingInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("INS", "Insurance"),
                            ("PAT", "Patient Self-Pay"),
                            ("ACC", "Client Account"),
                        ],
                        default="PAT",
                        max_length=3,
                    ),
                ),
                ("insurance_provider", models.CharField(blank=True, max_length=200)),
                ("policy_number", models.CharField(blank=True, max_length=100)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_info",
                        to="labs.testrequest",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="tenants.vendor",
                    ),
                ),
            ],
        ),
    ]
