# Generated by Django 5.2.7 on 2025-12-14 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_testrequest_clinical_indication_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff/clinician who approved patient self-order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Why was this order rejected?'),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='available_for_online_booking',
            field=models.BooleanField(default=False, help_text='Can patients request this test online without clinician referral?'),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='collection_instructions',
            field=models.TextField(blank=True, help_text="How the sample should be collected (e.g., 'First morning urine', 'Avoid recent exercise')"),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='patient_friendly_description',
            field=models.TextField(blank=True, help_text="Layman's explanation of what this test measures and why it's ordered"),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text="Patient-facing instructions (e.g., 'Fast for 8-12 hours', 'Avoid alcohol 48hrs before')"),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='preparation_required',
            field=models.BooleanField(default=False, help_text='Does this test require special preparation? (fasting, medication hold, etc.)'),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='requires_physician_approval',
            field=models.BooleanField(default=False, help_text='Patient orders require physician review before processing (used for complex/high-risk tests)'),
        ),
        migrations.AddField(
            model_name='vendortest',
            name='typical_reasons',
            field=models.TextField(blank=True, help_text='Common clinical indications for this test (for patient education)'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='clinical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='clinical_indication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='clinician_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='clinician_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='collection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='external_referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='has_informed_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='priority',
            field=models.CharField(choices=[('urgent', 'URGENT'), ('routine', 'ROUTINE')], default='routine', max_length=45),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='request_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Awaiting Approval'), ('A', 'Approved'), ('R', 'Received'), ('N', 'Analysis'), ('C', 'Complete'), ('V', 'Verified'), ('X', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='urgency_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['status', 'created_at'], name='labs_testre_status_13d82c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortest',
            index=models.Index(fields=['available_for_online_booking'], name='labs_vendor_availab_e7c7ad_idx'),
        ),
    ]
