# Generated by Django 5.2.7 on 2025-10-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_vendortest_created_at_vendortest_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
