# Generated by Django 5.2.7 on 2026-01-26 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_testassignment_released_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("reason", models.TextField()),
                ("amended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amended_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_history",
                        to="labs.testresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Amendment",
                "ordering": ["-amended_at"],
            },
        ),
    ]
