# Generated by Django 5.2.7 on 2025-11-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_alter_testrequest_priority_qclot_qcresult_qcaction_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billinginformation",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_info_drop",
                to="labs.testrequest",
            ),
        ),
        migrations.AlterField(
            model_name="billinginformation",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_records_drop",
                to="tenants.vendor",
            ),
        ),
    ]
