# Generated by Django 5.2.7 on 2026-01-31 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0003_resultamendment"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrequest",
            name="request_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="testrequest",
            constraint=models.UniqueConstraint(
                fields=("vendor", "request_id"), name="unique_request_id_per_vendor"
            ),
        ),
    ]
