# Generated by Django 5.2.7 on 2026-01-05 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0003_testrequest_approved_at_testrequest_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="testresult",
            name="labs_testre_assignm_fe411e_idx",
        ),
        migrations.RemoveIndex(
            model_name="testresult",
            name="labs_testre_release_0974c6_idx",
        ),
        migrations.RemoveIndex(
            model_name="testresult",
            name="labs_testre_data_so_e3c16e_idx",
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="released",
        ),
        migrations.AddField(
            model_name="testresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("verified", "Verified"),
                    ("released", "Released"),
                    ("amended", "Amended"),
                ],
                default="draft",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("instrument", "Instrument Generated"),
                    ("imported", "Imported"),
                    ("calculated", "Calculated"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="result_value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(fields=["status"], name="labs_testre_status_c62e01_idx"),
        ),
        migrations.AddIndex(
            model_name="testresult",
            index=models.Index(
                fields=["released_at"], name="labs_testre_release_528c38_idx"
            ),
        ),
    ]
