# Generated by Django 5.2.7 on 2026-02-03 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0004_alter_testrequest_request_id_and_more"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="sample_id",
            field=models.CharField(
                help_text="Globally unique barcode/sample ID (auto-generated).",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("vendor", "sample_id"), name="unique_sample_per_vendor"
            ),
        ),
    ]
