# Generated by Django 5.2.7 on 2026-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0004_remove_testresult_labs_testre_assignm_fe411e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_shadow",
            field=models.BooleanField(
                default=False,
                help_text="True if created via a walk-in appointment without a full account.",
            ),
        ),
    ]
