# Generated by Django 5.2.7 on 2026-02-03 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0005_alter_sample_sample_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
