# Generated by Django 5.2.7 on 2026-02-03 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0006_alter_testresult_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testassignment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
