# Generated by Django 5.2.7 on 2026-02-04 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0007_alter_testassignment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
