# Generated by Django 5.2.7 on 2026-02-04 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0008_alter_testrequest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
